Repository LiteFarmOrg/LiteFarm, pull requests merged in 2023-11, with the labels that each got.

#2939 LF-3761: Cleanup Quantity translations
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Forms/GeneralRevenue/CropSaleItem.jsx
  packages/webapp/src/components/Task/AddProduct/index.jsx
  packages/webapp/src/components/Task/HarvestingTask/ReadOnly.jsx
  packages/webapp/src/components/Task/HarvestingTask/index.jsx
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/Quantity.jsx
Labels: enhancement

#2937 LF-3746: Group transactions by date
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/src/components/Finances/Transaction/Mobile/List.jsx
  packages/webapp/src/components/Finances/Transaction/Mobile/styles.module.scss
  packages/webapp/src/containers/Finances/util.js
  packages/webapp/src/tests/financeUtil.test.js
  packages/webapp/src/util/date.js
Labels: enhancement

#2938 LF-3761: Implement crop sales expandable content
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/CropSaleTable.jsx
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/index.jsx
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/styles.module.scss
  packages/webapp/src/components/Finances/Transaction/Mobile/List.jsx
  packages/webapp/src/components/Finances/Transaction/Mobile/styles.module.scss
  packages/webapp/src/components/Table/v2/index.jsx
  packages/webapp/src/containers/Finances/TransactionList/index.jsx
  packages/webapp/src/containers/Finances/useTransactions.js
  packages/webapp/src/containers/Finances/util.js
  packages/webapp/src/stories/Table/TableV2.stories.jsx
  packages/webapp/src/tests/buildTransactions.test.jsx
Labels: enhancement

#2940 LF-3748 Implement labour type transaction expandable content
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/LabourTable.jsx
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/index.jsx
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/styles.module.scss
  packages/webapp/src/components/RouterTab/StateTab/index.jsx
Labels: enhancement

#2944 LF-3749: Iimplement other transactions expandable content
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/GeneralTransactionTable.jsx
  packages/webapp/src/components/Finances/Transaction/ExpandedContent/index.jsx
  packages/webapp/src/containers/Finances/OtherExpense/index.jsx
  packages/webapp/src/containers/Finances/index.jsx
Labels: enhancement

#2945 LF-3750 Add search to dashboard
  packages/webapp/src/components/Card/NoSearchResults/index.jsx
  packages/webapp/src/components/Finances/DateRangeSelector/index.jsx
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/index.jsx
  packages/webapp/src/components/Form/Input/index.jsx
  packages/webapp/src/components/Modals/index.jsx
  packages/webapp/src/components/PopupFilter/PureCollapsibleSearch/index.jsx
  packages/webapp/src/components/PopupFilter/PureCollapsibleSearch/styles.module.scss
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/styles.module.scss
  packages/webapp/src/containers/hooks/useSearchFilter.js
  packages/webapp/src/stories/PureCollapsibleSearch/PureCollapsibleSearch.stories.jsx
Labels: enhancement

#2952 LF-3797: Finance custom date range dropdown is shown under CardsCarrousel
  packages/webapp/src/components/DateRangeSelector/styles.module.scss
Labels: bug

#2951 LF-3788 The user is not able to type out a product name during the creation of the soil amendment task or clean task
  packages/webapp/src/components/Form/ReactSelect/index.jsx
Labels: bug

#2953 LF-3779 The field "Language preference" is missing when the user is creating the account using SSO method
  packages/webapp/src/components/CreateUserAccount/index.jsx
  packages/webapp/src/containers/SSOUserCreateAccountInfo/index.jsx
Labels: bug

#2930 LF-3753: Add floating button to add new expense/revenue
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/assets/theme/index.tsx
  packages/webapp/src/components/Button/FloatingActionButton/index.jsx
  packages/webapp/src/components/Button/FloatingActionButton/styles.module.scss
  packages/webapp/src/components/Finances/AddTransactionButton/index.jsx
  packages/webapp/src/components/Finances/AddTransactionButton/styles.module.scss
  packages/webapp/src/components/Form/DropDownButton/index.jsx
  packages/webapp/src/components/Form/DropDownButton/styles.module.scss
  packages/webapp/src/components/Menu/FloatingButtonMenu/FloatingMenu.jsx
  packages/webapp/src/components/Menu/FloatingButtonMenu/index.jsx
  packages/webapp/src/components/Menu/FloatingButtonMenu/styles.module.scss
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/styles.module.scss
  packages/webapp/src/stories/Button/DropdownButton.stories.jsx
  packages/webapp/src/stories/Button/FloatingActionButton.stories.jsx
  packages/webapp/src/stories/Menu/FloatingButtonMenu/FloatingButtonMenu.stories.jsx
  packages/webapp/src/stories/Menu/FloatingButtonMenu/FloatingMenu.stories.jsx
Labels: enhancement

#2955 LF-3601: The user is not able to change the unit of measurement after he adds another harvest use during the completion of the harvest task
  packages/webapp/src/components/Form/Unit/index.jsx
Labels: bug

#2956 LF-3604: Remove space in application title
  packages/api/src/templates/locales/fr.json
  packages/webapp/.storybook/preview-head.html
  packages/webapp/index.html
Labels: bug

#2948 LF-3545, LF-3634 Viewing the task list after another user has created new crop plans causes whitescreen type error crash
  packages/api/src/controllers/managementPlanController.js
  packages/api/src/models/managementPlanModel.js
  packages/webapp/src/containers/Crop/ManagementDetail/EditManagementDetails.jsx
  packages/webapp/src/containers/Crop/ManagementDetail/ManagementDetails.jsx
  packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
  packages/webapp/src/containers/Task/index.jsx
  packages/webapp/src/containers/managementPlanSlice.js
  packages/webapp/src/containers/taskSlice.js
Labels: bug

#2969 LF-3805: Add transaction menu is shown below expanded table header on mobile
  packages/webapp/src/components/Menu/FloatingButtonMenu/styles.module.scss
Labels: bug

#2958 LF-3755 Style xlsx finance report with ExcelJS API
  packages/api/src/controllers/exportController.js
  packages/api/src/util/generateFinanceReport.js
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/src/containers/Finances/Report/index.jsx
  packages/webapp/src/containers/Finances/Report/reportFormattingUtils.js
Labels: enhancement

#2970 LF-3666 An error message will be displayed failed to update revenue type once the user will try to rename the custom revenue type
  packages/api/src/controllers/farmExpenseTypeController.js
  packages/api/src/controllers/revenueTypeController.js
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Form/hookformValidationUtils.js
  packages/webapp/src/containers/Finances/CustomExpenseType/AddSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomExpenseType/EditSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/AddCustomRevenue.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
Labels: bug, enhancement

#2976 LF-3804 Dashboard and report filters should be sorted
  packages/webapp/src/containers/Filter/Transactions/index.jsx
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
  packages/webapp/src/containers/Finances/selectors.js
Labels: bug

#2979 LF-3666b Add retire vs delete distinction to finance types
  packages/api/db/migration/20231110195632_add-retire-vs-delete-distinction-to-finance-types.js
  packages/api/src/controllers/baseController.js
  packages/api/src/controllers/farmExpenseTypeController.js
  packages/api/src/controllers/revenueTypeController.js
  packages/api/src/models/expenseTypeModel.js
  packages/api/src/models/revenueTypeModel.js
  packages/api/tests/expense_type.test.js
  packages/api/tests/revenue_type.test.js
  packages/webapp/public/locales/en/message.json
  packages/webapp/src/components/Form/hookformValidationUtils.js
  packages/webapp/src/containers/Finances/CustomExpenseType/AddSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomExpenseType/EditSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/AddCustomRevenue.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
  packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
  packages/webapp/src/containers/Finances/RevenueDetail/index.jsx
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/Finances/selectors.js
  packages/webapp/src/containers/Finances/useCustomExpenseTypeTileContents.js
  packages/webapp/src/containers/Finances/util.js
  packages/webapp/src/containers/revenueTypeSlice.js
Labels: bug, enhancement

#2904 Add no-cache directive to index.html (Docker nginx)
  packages/webapp/nginx.conf
Labels: bug, enhancement

#2974 LF-3608: Although the success pop up message is displayed, the harvest task won't be created, it actually creates an empty harvest task.
  packages/webapp/src/components/Task/PureTaskCrops/index.jsx
  packages/webapp/src/containers/Task/TaskDate/index.jsx
Labels: bug

#2984 LF-3778c Clean up unused translations using i18n script
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
Labels: bug

#2983 LF-3814 The white screen is displayed once the user Updates the user info without actually selected the preferred LiteFarm Language
  packages/api/src/controllers/userController.js
Labels: bug

#2985 LF-3809: No actions are triggered once the user clicks on the "Upload" button, once the user added the csv file
  packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
Labels: bug

#2954 LF-3605, LF-3681 One of my farms is totally broken cant access any page of the app
  packages/api/src/controllers/managementPlanController.js
  packages/api/src/middleware/validation/deleteManagementPlan.js
  packages/api/src/routes/managementPlanRoute.js
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Modals/UnableToDeleteConcurrencyModal/index.jsx
  packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
  packages/webapp/src/containers/Crop/saga.js
  packages/webapp/src/stories/Modal/UnableToDeleteConcurrencyModal.stories.jsx
Labels: bug, enhancement

#2986 LF-3821 Failure when editing greenhouse details
  packages/api/src/models/greenhouseModel.js
Labels: bug

#2992 LF-3817 Unmount PureEnterPasswordPage when visibility changes
  packages/webapp/src/containers/CustomSignUp/index.jsx
Labels: bug

#2988 LF-3815 Distinguish retired and un retired types in filter views
  packages/webapp/src/containers/Filter/Transactions/index.jsx
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
  packages/webapp/src/containers/Finances/Report/index.jsx
  packages/webapp/src/containers/Finances/Report/reportFormattingUtils.js
  packages/webapp/src/containers/Finances/selectors.js
Labels: enhancement

#2994 LF-3825 the white screen is displayed on the mobile phone device once the user switches the farms and opens the finance dashboard
  packages/webapp/src/containers/Finances/actions.js
  packages/webapp/src/containers/Finances/constants.js
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/reducer.js
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/Finances/selectors.js
  packages/webapp/src/containers/saga.js
  packages/webapp/src/containers/taskSlice.js
Labels: bug

#3001 LF-3844 The user is not able to delete or abandon the crop plan once he deletes a task which is associated with this crop plan
  packages/api/src/controllers/managementPlanController.js
  packages/api/src/controllers/taskController.js
  packages/api/src/models/taskModel.js
Labels: bug

#2990 LF-3766: Labour costs for harvest task is not counted if the task did not have an assignee when it was created
  packages/api/src/controllers/taskController.js
  packages/api/tests/task.test.js
  packages/webapp/src/containers/Filter/Transactions/index.jsx
  packages/webapp/src/containers/Task/saga.js
Labels: bug

#3002 LF-3870: Search for expense does not work for all types
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
  packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
  packages/webapp/src/containers/Finances/util.js
Labels: bug

#3006 LF-3866 Could not download finance report
  packages/api/src/util/generateFinanceReport.js
Labels: bug

#3008 LF-3882 The "Save" button becomes disabled once the user changes the revenue type from "Crop Generated" to "No crop generated" once he tries to edit the revenue.
  packages/webapp/src/containers/Finances/useCropSaleInputs.jsx
Labels: bug

#3009 LF-3883 Can't edit the description of a type that shares the name of a deleted type
  packages/api/src/controllers/farmExpenseTypeController.js
  packages/api/src/controllers/revenueTypeController.js
Labels: bug

#3014 LF-3902 The white screen is displayed during the creation of a crop plan once the user will click on the "Germination" or "Initial harvest" field.
  packages/webapp/src/components/Form/InputDuration/index.jsx
Labels: bug

#3016 Fix: "date" in finance report export drawer
  packages/webapp/src/containers/Finances/Report/index.jsx
Labels: bug
