Repository LiteFarmOrg/LiteFarm, pull requests merged in 2023-09, with the labels that each got.

#2851 LF-3553: Updated multi select expense type view
  packages/api/db/migration/20230817213340_rename_expense_type_other_to_miscellaneous.js
  packages/api/src/controllers/farmExpenseTypeController.js
  packages/api/src/models/expenseTypeModel.js
  packages/webapp/public/locales/en/expense.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/expense.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/expense.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/expense.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/images/gear.svg
  packages/webapp/src/assets/images/log/bug.svg
  packages/webapp/src/assets/images/log/equipment.svg
  packages/webapp/src/assets/images/log/fertilizing.svg
  packages/webapp/src/assets/images/log/fuel.svg
  packages/webapp/src/assets/images/log/land.svg
  packages/webapp/src/assets/images/log/machinery.svg
  packages/webapp/src/assets/images/log/miscellaneous.svg
  packages/webapp/src/assets/images/log/other.svg
  packages/webapp/src/assets/images/log/seeding.svg
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/index.jsx
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/styles.module.scss
  packages/webapp/src/components/Tile/IconLabelTile.jsx
  packages/webapp/src/components/Tile/styles.module.scss
  packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
  packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/styles.module.scss
  packages/webapp/src/containers/Finances/OtherExpense/index.jsx
  packages/webapp/src/containers/Finances/actions.js
  packages/webapp/src/containers/Finances/constants.js
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/reducer.js
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/Finances/selectors.js
  packages/webapp/src/containers/Finances/styles.module.scss
  packages/webapp/src/stories/Pages/Finance/PureFinanceTypeSelection.stories.jsx
  packages/webapp/src/stories/Tile/IconLabelTile.stories.jsx
  packages/webapp/src/stories/Tile/Tiles.stories.jsx
Labels: enhancement

#2857 LF-3581 Create revenue types table and model and add references to other tables where appropriate
  packages/api/db/migration/20230831015743_create_revenue_type_table.js
  packages/api/src/models/revenueTypeModel.js
  packages/api/src/models/saleModel.js
  packages/api/tests/sale.test.js
Labels: enhancement

#2861 LF-3586 make the revenue type slice and add the revenue types selector and sagas
  packages/webapp/public/locales/en/message.json
  packages/webapp/public/locales/es/message.json
  packages/webapp/public/locales/fr/message.json
  packages/webapp/public/locales/pt/message.json
  packages/webapp/src/apiConfig.js
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/revenueTypeSlice.js
  packages/webapp/src/store/reducer.js
Labels: enhancement

#2858 LF-3582: Refactor the add expense container to updated style
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
  packages/webapp/src/components/Finances/AddExpense/constants.jsx
  packages/webapp/src/components/Finances/AddExpense/index.jsx
  packages/webapp/src/components/Finances/AddExpense/styles.module.scss
  packages/webapp/src/components/RepeatCropPlan/utils.js
  packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
  packages/webapp/src/containers/Finances/NewExpense/AddExpense/styles.module.scss
  packages/webapp/src/stories/Pages/Finance/ExpenseItemInputs.stories.js
  packages/webapp/src/util/date.jsx
Labels: enhancement

#2863 LF-3583: Create select revenue type container and add to routes
  packages/webapp/public/locales/en/revenue.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/revenue.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/revenue.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/revenue.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/Routes.jsx
  packages/webapp/src/assets/images/log/crop_sale.svg
  packages/webapp/src/assets/images/log/custom_revenue.svg
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/revenueTypeSlice.js
  packages/webapp/src/stories/Pages/Finance/PureFinanceTypeSelection.stories.jsx
Labels: enhancement

#2860 LF-3592: Create custom revenue type form container and frontend route
  packages/api/db/migration/20230913181516_add_columns_to_sale.js
  packages/api/src/middleware/validation/sale.js
  packages/api/src/models/saleModel.js
  packages/api/tests/mock.factories.js
  packages/api/tests/sale.test.js
  packages/api/tests/testEnvironment.js
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/index.jsx
  packages/webapp/src/components/Forms/CropSale/index.jsx
  packages/webapp/src/components/Forms/CropSale/styles.module.scss
  packages/webapp/src/components/Forms/GeneralRevenue/index.jsx
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
  packages/webapp/src/containers/Finances/AddSale/index.jsx
  packages/webapp/src/containers/Finances/EditSale/index.jsx
  packages/webapp/src/stories/Finances/GeneralIncome.stories.jsx
Labels: enhancement

#2859 LF-3554: Create custom expense types tile view
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/Routes.jsx
  packages/webapp/src/components/Forms/ManageCustomTypes/index.jsx
  packages/webapp/src/components/Forms/SimpleCustomType/index.jsx
  packages/webapp/src/containers/Finances/CustomExpenseType/AddSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomExpenseType/EditSimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/CustomExpenseType/ReadOnlySimpleCustomExpense.jsx
  packages/webapp/src/containers/Finances/ManageCustomExpenseTypes/index.jsx
  packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
  packages/webapp/src/containers/Finances/useCustomExpenseTypeTileContents.js
  packages/webapp/src/stories/Pages/Forms/ManageCustomTypes.stories.jsx
Labels: enhancement

#2870 LF-3627 Update the edit individual expense flow
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/Routes.jsx
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
  packages/webapp/src/components/Finances/AddExpense/constants.jsx
  packages/webapp/src/components/Finances/PureExpenseDetail/index.jsx
  packages/webapp/src/components/Form/Input/input.module.scss
  packages/webapp/src/components/Forms/SimpleCustomType/index.jsx
  packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/index.jsx
  packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/styles.module.scss
  packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
  packages/webapp/src/containers/Finances/ExpenseDetail/styles.module.scss
  packages/webapp/src/containers/Finances/OtherExpense/index.jsx
  packages/webapp/src/containers/Finances/actions.js
  packages/webapp/src/containers/Finances/constants.js
  packages/webapp/src/containers/Finances/reducer.js
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/Finances/selectors.js
  packages/webapp/src/stories/Pages/Finance/PureExpenseDetail.stories.jsx
Labels: enhancement

#2880 LF-3649 Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
  packages/api/src/controllers/farmExpenseTypeController.js
Labels: bug

#2876 LF-3643 Fix AddExpense value Input for Portuguese
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
Labels: bug

#2882 LF-3651 Revenue type table unique violation error on auto-incrementing primary key
  packages/api/db/migration/20230831015743_create_revenue_type_table.js
  packages/api/src/middleware/validation/sale.js
  packages/api/tests/sale.test.js
Labels: bug

#2886 LF-3591 Create the revenueType backend api (route and controller) and the get all types function
  packages/api/src/controllers/baseController.js
  packages/api/src/controllers/revenueTypeController.js
  packages/api/src/routes/revenueTypeRoute.js
  packages/api/tests/revenue_type.test.js
Labels: enhancement

#2878 LF-3599: Review finances dashboard and check that new custom expenses and revenues function properly in these views
  packages/api/src/controllers/saleController.js
  packages/api/tests/sale.test.js
  packages/webapp/src/components/Forms/GeneralRevenue/index.jsx
  packages/webapp/src/containers/Finances/ActualCropRevenue/index.jsx
  packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
  packages/webapp/src/containers/Finances/ActualRevenueItem/index.jsx
  packages/webapp/src/containers/Finances/AddSale/index.jsx
  packages/webapp/src/containers/Finances/EditSale/index.jsx
  packages/webapp/src/containers/Finances/OtherExpense/index.jsx
  packages/webapp/src/containers/Finances/constants.js
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/util.js
Labels: enhancement

#2881 LF-3586 Add pathing to manage_custom_revenues
  packages/webapp/src/containers/Finances/saga.js
Labels: enhancement

#2887 LF-3660 Add optional port variable to test config
  packages/api/.env.default
  packages/api/.knex/knexfile.js
Labels: documentation, enhancement

#2889 LF-3663 The white screen will be displayed once the user will create the revenue type with an exact name that he has previously deleted
  packages/api/src/controllers/revenueTypeController.js
Labels: bug

#2890 LF-3626: Persist data in expense form
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
  packages/webapp/src/components/Finances/AddExpense/index.jsx
Labels: enhancement

#2892 LF-3599: Fix total revenue calculation and general revenue values
  packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/util.js
Labels: bug

#2891 LF-3662: "< " Back arrow redirectes to the wrong page when the user saves the "Custom Revenue Type"
  packages/webapp/src/containers/Finances/CustomRevenueType/AddCustomRevenue.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
  packages/webapp/src/containers/Finances/CustomRevenueType/ReadOnlyCustomRevenue.jsx
  packages/webapp/src/containers/Finances/ManageCustomRevenueTypes/index.jsx
Labels: bug
