Repository LiteFarmOrg/LiteFarm, pull requests merged in 2023-12, with the labels that each got.

#3025 LF-3914 Post (some) handled errors to Sentry
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/common/logger.js
Labels: enhancement

#3027 LF-3921a Update Nginx configuration to match vite-pwa recommendations
  packages/webapp/nginx.conf
Labels: bug, enhancement

#3028 LF-3921b Remove navbar gradient (test code change)
  packages/webapp/src/components/Navigation/NavBar/index.jsx
Labels: bug

#3020 LF-3085: Add a linter for translations files
  .github/workflows/lint_translation_files.yml
  packages/webapp/.eslintrc.json
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
Labels: enhancement

#3023 LF-3881 Return better errors by default from the API
  packages/api/src/common/logger.js
  packages/api/src/controllers/cropVarietyController.js
  packages/api/src/controllers/documentController.js
  packages/api/src/controllers/insightController.js
  packages/api/src/controllers/managementPlanController.js
  packages/api/src/controllers/organicHistoryController.js
  packages/api/src/controllers/taskController.js
Labels: enhancement

#3026 LF-3910: Fix side menu on the left for desktop and tablet views
  packages/webapp/src/App.jsx
  packages/webapp/src/assets/variables.scss
  packages/webapp/src/components/Navigation/NavBar/index.jsx
  packages/webapp/src/components/Navigation/NavBar/slideMenu/index.jsx
  packages/webapp/src/components/Navigation/NavBar/slideMenu/styles.module.scss
  packages/webapp/src/components/Navigation/NavBar/styles.module.scss
  packages/webapp/src/containers/Map/styles.module.scss
  packages/webapp/src/containers/Navigation/SlideMenu.jsx
  packages/webapp/src/containers/Navigation/index.jsx
  packages/webapp/src/hooks/useIsFarmSelected.jsx
  packages/webapp/src/stories/Navigation/NavBarDrawer.stories.jsx
  packages/webapp/src/styles.module.scss
Labels: enhancement

#3044 LF-3085 update Lint Translation Files github workflow for /api
  .github/workflows/lint_translation_files.yml
  packages/api/.eslintrc.cjs
  packages/api/package-lock.json
  packages/api/package.json
Labels: enhancement

#3024 LF-3915 Clean up 'docker compose up' for new contributors
  README.md
  docker-compose.yml
  packages/api/dev.export.sh
Labels: enhancement

#3055 LF-3932: Fix broken styles due to navigation update
  packages/webapp/src/App.jsx
  packages/webapp/src/components/ChooseFarm/index.jsx
  packages/webapp/src/components/Navigation/SideMenu/index.jsx
  packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
  packages/webapp/src/components/Navigation/TopMenu/styles.module.scss
  packages/webapp/src/components/Navigation/index.jsx
  packages/webapp/src/components/Profile/People/index.jsx
  packages/webapp/src/components/WeatherBoard/assets/weatherBoard.module.scss
  packages/webapp/src/containers/Navigation/index.jsx
  packages/webapp/src/styles.module.scss
Labels: bug
