Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-09, with the labels that each got.

#3402 Add animal fixes
  packages/webapp/src/components/Animals/AddAnimalsSummaryCard/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts
Labels: bug

#3397 LF-4166 (4): Implement end to end animal creation flow
  packages/api/src/models/animalModel.js
  packages/webapp/src/components/Animals/AddAnimalsSummaryCard/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/types.ts
  packages/webapp/src/containers/Animals/AddAnimals/utils.ts
  packages/webapp/src/store/api/types/index.ts
  packages/webapp/src/stories/Animals/Details/mockData.ts
  packages/webapp/src/types/index.ts
Labels: enhancement

#3416 LF-4056 Language selector needs to provide list of language in their native form
  packages/webapp/public/locales/de/translation.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/hi/translation.json
  packages/webapp/public/locales/ml/translation.json
  packages/webapp/public/locales/pa/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/hooks/useLanguageOptions.ts
Labels: enhancement

#3424 LF-4403 Add translated pdf files to the appropriate place
  packages/api/src/jobs/locales/de/readme.pdf
  packages/api/src/jobs/locales/hi/readme.pdf
  packages/api/src/jobs/locales/pa/readme.pdf
Labels: enhancement

#3427 LF-4221 investigate moment date locale and modify if necessary
  packages/webapp/src/components/CropCatalogue/CropStatusInfoBox/index.jsx
  packages/webapp/src/components/MonthCalendar/index.jsx
  packages/webapp/src/components/RepeatCropPlan/index.jsx
  packages/webapp/src/components/RepeatCropPlan/utils.js
  packages/webapp/src/containers/Documents/index.jsx
  packages/webapp/src/util/moment.js
Labels: bug

#3436 LF-4056b Fix for language selector dropdown
  packages/webapp/src/components/Profile/Account/index.jsx
  packages/webapp/src/hooks/useLanguageOptions.ts
Labels: bug

#3443 LF-4438 Language dropdown ruins layout of page
  packages/webapp/src/components/Form/ReactSelect/Select.tsx
Labels: bug, enhancement

#3444 LF-4419 Add the three new welcome screen SVGs
  packages/webapp/src/assets/images/signUp/signup_german.svg
  packages/webapp/src/assets/images/signUp/signup_hindi.svg
  packages/webapp/src/assets/images/signUp/signup_punjabi.svg
  packages/webapp/src/components/WelcomeScreen/index.jsx
Labels: enhancement

#3442 LF-4429 Gender dropdown which by default has prefer not to say selected does not update when changing language
  packages/webapp/src/components/CreateUserAccount/index.jsx
  packages/webapp/src/components/InviteUser/index.jsx
  packages/webapp/src/components/InvitedUserCreateAccount/index.jsx
  packages/webapp/src/components/Profile/Account/index.jsx
  packages/webapp/src/components/Profile/EditUser/index.jsx
  packages/webapp/src/hooks/useGenderOptions.jsx
Labels: bug

#3447 LF-4437 Remove incomplete languages from dropdown before German release
  packages/api/src/jobs/locales/i18n.js
  packages/api/src/jobs/locales/i18next-parser.config.js
  packages/api/src/templates/sendEmailTemplate.js
  packages/webapp/src/components/WelcomeScreen/index.jsx
  packages/webapp/src/containers/Consent/index.jsx
  packages/webapp/src/hooks/useLanguageOptions.ts
  packages/webapp/src/locales/i18n.js
  packages/webapp/src/locales/i18next-parser.config.cjs
Labels: enhancement

#3465 Run API tests on patch branches
  .github/workflows/automated_tests.yml
Labels: enhancement

#3400 LF-4405: floating menu button looks different from what is designed
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/components/Button/FloatingActionButton/styles.module.scss
  packages/webapp/src/components/Menu/FloatingButtonMenu/index.jsx
  packages/webapp/src/components/Menu/FloatingButtonMenu/styles.module.scss
Labels: enhancement

#3478 LF-4413 The white screen is displayed once the user tries to complete the creation of the new animal type
  packages/webapp/src/containers/Animals/AddAnimals/utils.ts
  packages/webapp/src/store/api/apiSlice.ts
Labels: bug
