Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-11, with the labels that each got.

#3501 LF-4470: Write database migration for animal movement task
  packages/api/db/migration/20241016204145_create_animal_movement_task_tables.js
Labels: enhancement

#3522 LF-4523: Animals internal identifier changes after data updates
  packages/api/db/migration/20241108052304_update_animal_union_batch_internal_id_view.js
  packages/api/db/sql/20241108052304_animal_union_batch_id_view.sql
  packages/api/tests/animal_union_batch.test.js
Labels: bug

#3518 LF-4471: Add or update models for animal movement task
  packages/api/src/controllers/taskController.js
  packages/api/src/models/animalBatchModel.js
  packages/api/src/models/animalModel.js
  packages/api/src/models/animalMovementPurposeModel.js
  packages/api/src/models/animalMovementTaskModel.js
  packages/api/src/models/animalMovementTaskPurposeRelationshipModel.js
  packages/api/src/models/taskAnimalBatchRelationshipModel.js
  packages/api/src/models/taskAnimalRelationshipModel.js
  packages/api/src/models/taskModel.js
Labels: enhancement

#3524 LF-4472: Update controllers and middleware to support animal movement task
  packages/api/src/controllers/animalBatchController.js
  packages/api/src/controllers/animalController.js
  packages/api/src/controllers/taskController.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/models/animalBatchModel.js
  packages/api/src/models/animalModel.js
  packages/api/src/models/locationModel.js
  packages/api/src/util/animal.js
Labels: enhancement

#3500 LF-4383 Animal details form container handle edit of animal details
  packages/api/src/models/animalBatchModel.js
  packages/webapp/public/locales/de/message.json
  packages/webapp/public/locales/en/message.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/message.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/message.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/message.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Animals/AddAnimalsDetails/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsForm/AnimalFormHeaderItem/index.tsx
  packages/webapp/src/components/Animals/AnimalBatchBasicInfo/index.tsx
  packages/webapp/src/components/Animals/AnimalBatchBasicInfo/styles.module.scss
  packages/webapp/src/components/Animals/DetailCards/General.tsx
  packages/webapp/src/components/Animals/DetailCards/Origin.tsx
  packages/webapp/src/components/Animals/DetailCards/Other.tsx
  packages/webapp/src/components/Animals/DetailCards/Unique.tsx
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/Form/ContextForm/index.tsx
  packages/webapp/src/components/Form/InputAutoSize/index.jsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/types.ts
  packages/webapp/src/containers/Animals/AddAnimals/useAnimalOptions.ts
  packages/webapp/src/containers/Animals/AddAnimals/utils.ts
  packages/webapp/src/containers/Animals/SingleAnimalView/AnimalReadonlyEdit.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/useInitialAnimalData.ts
  packages/webapp/src/containers/Animals/SingleAnimalView/utils.ts
  packages/webapp/src/routes/AnimalsRoutes.jsx
  packages/webapp/src/store/api/apiSlice.ts
  packages/webapp/src/store/api/types/index.ts
  packages/webapp/src/stories/Animals/Details/AnimalDetails.stories.tsx
  packages/webapp/src/stories/Animals/Details/BatchDetails.stories.tsx
  packages/webapp/src/stories/Animals/Details/General.stories.tsx
  packages/webapp/src/stories/Animals/Details/mockData.ts
Labels: enhancement

#3533 LF-4531: Set up new task abandonment reason for tasks with removed animals
  packages/api/db/migration/20241118191954_add_constraint_to_task_abandonment_reason.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/models/taskModel.js
  packages/api/tests/task.test.js
  packages/webapp/public/locales/en/translation.json
Labels: enhancement

#3547 LF-4475 [Nice to have] Update layout for manage custom tasks
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/CantFindCustomType/index.tsx
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/CantFindCustomType/styles.module.scss
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
  packages/webapp/src/components/Task/PureTaskTypeSelection/styles.module.scss
  packages/webapp/src/stories/CantFindCustomType/CantFindCustomType.stories.tsx
Labels: enhancement

#3540 LF-4474 [Nice to have] convert create task button to CTA floating button
  packages/end-to-end/cypress/e2e/tasks.js
  packages/webapp/src/components/Animals/Inventory/index.tsx
  packages/webapp/src/components/Animals/Inventory/styles.module.scss
  packages/webapp/src/components/Button/FloatingActionButton/styles.module.scss
  packages/webapp/src/components/Task/TaskCount/index.jsx
  packages/webapp/src/containers/Task/index.jsx
  packages/webapp/src/containers/Task/styles.module.scss
Labels: enhancement

#3535 LF-4372 Feedback - move feedback form and delete old routes
  packages/webapp/public/locales/de/translation.json
  packages/webapp/public/locales/en/message.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/hi/translation.json
  packages/webapp/public/locales/ml/translation.json
  packages/webapp/public/locales/pa/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/images/navbar/help.svg
  packages/webapp/src/components/Drawer/style.module.scss
  packages/webapp/src/components/Form/Button/button.module.scss
  packages/webapp/src/components/Form/Button/index.tsx
  packages/webapp/src/components/Form/form.module.scss
  packages/webapp/src/components/Help/index.jsx
  packages/webapp/src/components/Help/styles.module.scss
  packages/webapp/src/components/ImagePicker/index.tsx
  packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
  packages/webapp/src/containers/FeedbackSurvey/index.jsx
  packages/webapp/src/containers/FeedbackSurvey/styles.module.scss
  packages/webapp/src/containers/Help/index.jsx
  packages/webapp/src/containers/Help/saga.js
  packages/webapp/src/routes/index.jsx
  packages/webapp/src/stories/Button/Button.stories.jsx
Labels: enhancement, new translations

#3534 LF-4384: End to end animal details
  packages/api/src/controllers/animalBatchController.js
  packages/api/src/middleware/validation/checkAnimalOrBatch.js
  packages/webapp/src/App.jsx
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
  packages/webapp/src/components/Animals/AnimalSingleViewHeader/index.tsx
  packages/webapp/src/components/Animals/AnimalSingleViewHeader/styles.module.scss
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/Form/ContextForm/index.tsx
  packages/webapp/src/components/Form/DropDownButton/index.jsx
  packages/webapp/src/components/Menu/MeatballsMenu/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/containers/Animals/Inventory/useAnimalOrBatchRemoval.ts
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/styles.module.scss
  packages/webapp/src/containers/Animals/SingleAnimalView/useInitialAnimalData.ts
  packages/webapp/src/types/index.ts
  packages/webapp/src/util/animal.ts
Labels: enhancement

#3550 LF-4479: [GET&POST] Update Task saga to account for new animal movement task
  packages/api/src/controllers/taskController.js
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/containers/Task/sagaUtils.js
  packages/webapp/src/containers/slice/taskSlice/animalMovementTaskSlice.js
  packages/webapp/src/containers/taskSlice.js
  packages/webapp/src/store/reducer.js
  packages/webapp/src/util/task.ts
Labels: enhancement

#3555 LF-4549: Sex-Detail Field Not Editable on Edit Animal Details Page
  packages/webapp/src/components/Form/SexDetails/index.tsx
Labels: bug
