Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-06, with the labels that each got.

#3217 LF-4240: April 2024 data policy updates (Version 6: May 31, 2024)
  packages/api/db/migration/20240603204923_reset_has_consent.js
  packages/webapp/src/containers/Consent/index.jsx
  packages/webapp/src/containers/Consent/locales/en/Owner.Consent.md
  packages/webapp/src/containers/Consent/locales/en/Worker.Consent.md
  packages/webapp/src/containers/Consent/locales/es/Owner.Consent.md
  packages/webapp/src/containers/Consent/locales/es/Worker.Consent.md
  packages/webapp/src/containers/Consent/locales/fr/Owner.Consent.md
  packages/webapp/src/containers/Consent/locales/fr/Worker.Consent.md
  packages/webapp/src/containers/Consent/locales/pt/Owner.Consent.md
  packages/webapp/src/containers/Consent/locales/pt/Worker.Consent.md
  packages/webapp/src/util/constants.js
Labels: enhancement

#3219 LF-4222: Fix sticky top bar
  packages/webapp/src/components/Navigation/styles.module.scss
Labels: bug

#3229 LF-4256 (2): Old consent version is shown after setting has consent to false
  packages/webapp/src/containers/userFarmSlice.ts
Labels: bug

#3228 LF-4212: Fix "Add another (expense) item" button and adapt it to the new design
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
  packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
  packages/webapp/src/components/Finances/AddExpense/styles.module.scss
Labels: bug

#3234 LF-4216 - Add case to insert null values when quantity does not exist
  packages/api/db/migration/20240504185218_create_soil_amendement_task_products_table.js
Labels: bug

#3233 LF-4230 Create a switch component
  packages/webapp/.storybook/preview.jsx
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/components/Form/Switch/index.jsx
  packages/webapp/src/components/Form/Switch/index.tsx
  packages/webapp/src/components/Form/Switch/styles.module.scss
  packages/webapp/src/stories/Form/Switch/Switch.stories.jsx
Labels: enhancement

#3212 LF-4220: Create new add products component for soil amendment
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/images/edit-02.svg
  packages/webapp/src/assets/images/plus-circle.svg
  packages/webapp/src/assets/mixin.scss
  packages/webapp/src/components/Form/Button/SmallButton.tsx
  packages/webapp/src/components/Form/Button/button.module.scss
  packages/webapp/src/components/Form/CompositionInputs/NumberInputWithSelect.tsx
  packages/webapp/src/components/Form/CompositionInputs/index.tsx
  packages/webapp/src/components/Form/InFormButtons/index.tsx
  packages/webapp/src/components/Task/AddProduct/index.jsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/Buttons.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/index.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/styles.module.scss
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/types.ts
  packages/webapp/src/containers/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/containers/Task/TaskDetails/index.jsx
  packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Task/constants.js
  packages/webapp/src/containers/productSlice.js
  packages/webapp/src/stories/Button/SmallButton.stories.tsx
  packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
  packages/webapp/src/stories/Pages/Task/AddSoilAmendmentProducts/AddSoilAmendmentProducts.stories.tsx
  packages/webapp/src/stories/Pages/Task/AddSoilamendmentProducts/products.ts
Labels: enhancement

#3230 LF-4238: Fix cleared filters on the Finances page
  packages/webapp/src/containers/Finances/TransactionFilter/index.jsx
Labels: bug

#3238 Fix directory path of AddSoilAmendmentProducts/products.ts for story
  packages/webapp/src/stories/Pages/Task/AddSoilAmendmentProducts/products.ts
Labels: bug

#3232 Remove pug dependabot
  packages/api/package-lock.json
  packages/api/package.json
Labels: dependencies

#3236 LF-4248: Make composition inputs component reusable
  packages/webapp/src/assets/images/ratio-option.svg
  packages/webapp/src/components/Form/CompositionInputs/NumberInputWithSelect.tsx
  packages/webapp/src/components/Form/CompositionInputs/index.tsx
  packages/webapp/src/components/Form/CompositionInputs/styles.module.scss
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/types.ts
  packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
  packages/webapp/src/stories/Pages/Task/AddSoilAmendmentProducts/products.ts
Labels: enhancement

#3265 LF-4249 Translation strings for Create QuantityApplicationRate component
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
Labels: enhancement

#3268 LF-4251 (0): Translation strings for additional soil amendment product inputs
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
Labels: enhancement

#3270 LF-4249 Amend translation string
  packages/webapp/public/locales/en/translation.json
Labels: bug

#3277 LF-4221 (0): Translations for application method
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Task/SoilAmendmentTask/index.jsx
Labels: enhancement
