Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-12, with the labels that each got.

#3530 Lf 4483 create selected animals summary component
  packages/webapp/public/locales/de/translation.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/hi/translation.json
  packages/webapp/public/locales/ml/translation.json
  packages/webapp/public/locales/pa/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Animals/FixedHeaderContainer/index.tsx
  packages/webapp/src/components/Animals/Inventory/index.tsx
  packages/webapp/src/components/Expandable/ExpandableItem.jsx
  packages/webapp/src/components/Expandable/styles.module.scss
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/styles.module.scss
  packages/webapp/src/components/PageTitle/MultiStepPageTitle/index.jsx
  packages/webapp/src/components/Pill/index.jsx
  packages/webapp/src/components/Table/TableV2.jsx
  packages/webapp/src/components/Table/styles.module.scss
  packages/webapp/src/components/Table/types.ts
  packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
  packages/webapp/src/components/Task/TaskLocations/index.jsx
  packages/webapp/src/components/Task/TaskLocations/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/Inventory/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/useFilteredInventory.ts
  packages/webapp/src/containers/Task/TaskLocations/index.jsx
  packages/webapp/src/stories/ExpandableItem/ExpandableItem.stories.jsx
  packages/webapp/src/stories/Table/TableV2.stories.jsx
Labels: new translations

#3527 LF-4481: Add Location to animal inventory UI
  packages/webapp/src/components/Animals/AnimalSingleViewHeader/index.tsx
  packages/webapp/src/components/Table/Cell/CellTypes/HoverPillOverflow.tsx
  packages/webapp/src/components/Table/Cell/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/Inventory/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
  packages/webapp/src/containers/Animals/Inventory/useFilteredInventory.ts
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/containers/Filter/Animals/index.tsx
  packages/webapp/src/containers/Filter/types.ts
  packages/webapp/src/store/api/types/index.ts
  packages/webapp/src/stories/Animals/AnimalSingleViewHeader.stories.tsx
  packages/webapp/src/stories/Animals/mockData.ts
  packages/webapp/src/stories/Table/TableCells.stories.jsx
  packages/webapp/src/types/index.ts
Labels: enhancement

#3557 LF-4555: Update getTasksForFarm to return all custom tasks in GET API response
  packages/api/src/controllers/taskController.js
  packages/api/tests/task.test.js
Labels: enhancement

#3559 LF-4553 Allow completing custom tasks with no associated locations
  packages/api/src/middleware/acl/hasFarmAccess.js
  packages/api/src/routes/taskRoute.js
Labels: enhancement

#3560 LF-4554 Adjust frontend task view to handle tasks with no locations
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Task/taskCardContentSelector.js
Labels: enhancement, new translations

#3558 LF-4538: Breed sorting does not work in inventory table
  packages/webapp/src/tests/sort.test.js
  packages/webapp/src/util/sort.ts
Labels: bug

#3554 LF-4528: Hide created in error option for animals with completed tasks
  packages/api/src/controllers/animalBatchController.js
  packages/api/src/controllers/animalController.js
  packages/api/src/models/animalBatchModel.js
  packages/api/src/models/animalModel.js
  packages/api/tests/animal.test.js
  packages/api/tests/animal_batch.test.js
  packages/webapp/src/components/Animals/RemoveAnimalsModal/index.tsx
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
  packages/webapp/src/containers/Animals/Inventory/useAnimalOrBatchRemoval.ts
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/store/api/types/index.ts
  packages/webapp/src/stories/Animals/mockData.ts
Labels: enhancement

#3561 Lf 4556 update location selection validation to allow zero locations using new checkbox flow
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Form/Checkbox/checkbox.module.scss
  packages/webapp/src/components/Form/Switch/index.tsx
  packages/webapp/src/components/Form/Switch/styles.module.scss
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/styles.module.scss
  packages/webapp/src/components/Task/TaskLocations/index.jsx
  packages/webapp/src/components/Task/TaskLocations/styles.module.scss
  packages/webapp/src/containers/Task/TaskLocations/index.jsx
  packages/webapp/src/containers/Task/useIsTaskType.js
Labels: new translations

#3546 LF-4527: Handle animal deletion and abandon related tasks
  packages/api/src/controllers/animalBatchController.js
  packages/api/src/controllers/animalController.js
  packages/api/src/middleware/validation/checkAnimalOrBatch.js
  packages/api/src/models/animalBatchModel.js
  packages/api/src/models/animalModel.js
  packages/api/src/models/taskModel.js
  packages/api/src/util/animal.js
  packages/api/tests/animal.test.js
  packages/api/tests/animalAndAnimalBatchCommon.test.js
  packages/api/tests/animal_batch.test.js
  packages/api/tests/task.test.js
  packages/api/tests/utils/animalUtils.js
  packages/api/tests/utils/taskUtils.js
  packages/webapp/src/containers/Animals/Inventory/useAnimalOrBatchRemoval.ts
  packages/webapp/src/store/api/apiSlice.ts
Labels: enhancement

#3552 LF-4545 Adjust read only task view for movement tasks
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Form/ReactSelect/styles.ts
  packages/webapp/src/components/Task/MovementTask/index.tsx
  packages/webapp/src/components/Task/MovementTask/styles.module.scss
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskLocations/index.jsx
  packages/webapp/src/components/Task/TaskLocations/styles.module.scss
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/components/Task/TaskReadOnly/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/styles.module.scss
  packages/webapp/src/util/task.ts
Labels: enhancement

#3571 Invalidate animal tags when movement task is completed
  packages/webapp/src/containers/Task/saga.js
Labels: enhancement

#3553 LF-4548 Adjust task complete (StepOne) view for movement tasks
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/components/Animals/Inventory/index.tsx
  packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
  packages/webapp/src/components/Task/TaskComplete/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/Inventory/styles.module.scss
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/containers/Task/sagaUtils.js
  packages/webapp/src/util/task.ts
Labels: enhancement, new translations

#3565 LF-4542: Allow custom task to have related animal ids on the backend
  packages/api/src/controllers/taskController.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/routes/taskRoute.js
  packages/api/src/util/task.js
  packages/api/tests/animalTask.test.js
  packages/api/tests/task.test.js
Labels: enhancement

#3562 Lf 4541 add animal inventory to custom task
  packages/webapp/public/locales/de/translation.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/hi/translation.json
  packages/webapp/public/locales/pa/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Task/PureTaskAssignment/index.jsx
  packages/webapp/src/components/Task/PureTaskCrops/index.jsx
  packages/webapp/src/components/Task/PureTaskDetails/index.jsx
  packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
  packages/webapp/src/components/Task/TaskDate/index.jsx
  packages/webapp/src/components/Task/TaskLocations/index.jsx
  packages/webapp/src/containers/Animals/Inventory/useAnimalsExist.tsx
  packages/webapp/src/containers/Task/TaskAnimalInventory/index.jsx
  packages/webapp/src/containers/Task/TaskAssignment/index.jsx
  packages/webapp/src/containers/Task/TaskCrops/index.jsx
  packages/webapp/src/containers/Task/TaskDate/index.jsx
  packages/webapp/src/containers/Task/TaskLocations/index.jsx
  packages/webapp/src/containers/Task/constants.js
  packages/webapp/src/containers/Task/util.js
Labels: new translations

#3574 LF-4558: Adjust tasks for farms with no animals
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
  packages/webapp/src/components/Task/getSupportedTaskTypesSet.js
  packages/webapp/src/containers/Animals/Inventory/useAnimalsExist.tsx
  packages/webapp/src/containers/Task/TaskTypeSelection/index.jsx
Labels: enhancement

#3581 LF-4558 Give second argument to getSupportedTaskTypes
  packages/webapp/src/containers/Filter/Tasks/index.jsx
  packages/webapp/src/containers/Task/index.jsx
Labels: bug

#3572 LF-4567 Allow custom tasks with animals to be editable on complete
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
  packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
Labels: enhancement

#3585 LF-4569 It is not possible to complete any kind of task if you choose that you have done some changes to the task
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
Labels: bug

#3586 LF-4577: Remove animal task dates validation
  packages/api/src/middleware/validation/checkAnimalOrBatch.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/routes/taskRoute.js
  packages/api/src/util/animal.js
  packages/api/tests/animalAndAnimalBatchCommon.test.js
  packages/api/tests/animalTask.test.js
Labels: bug

#3592 LF-4595 The app crashes when trying to access deleted animal’s details page
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
Labels: bug

#3588 LF-4568 fix sex filter
  packages/webapp/src/containers/Animals/Inventory/useFilteredInventory.ts
Labels: bug

#3593 LF-4575 fix custom tasks not attached to crop plans
  packages/webapp/src/containers/Task/TaskLocations/index.jsx
Labels: bug

#3589 LF-4579: Recording a movement task in the past messes up animals location
  packages/api/src/controllers/taskController.js
  packages/api/src/models/animalBatchModel.js
  packages/api/src/models/animalModel.js
  packages/api/tests/animalTask.test.js
Labels: bug

#3590 LF-4592, LF-4587 Animal movement purpose form persistence and reset bugs
  packages/webapp/src/components/Task/MovementTask/index.tsx
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/util/task.ts
Labels: bug

#3587 LF-4551 App crashes if trying to complete a custom task via the "task has already been completed" flow
  packages/webapp/src/components/Task/TaskComplete/index.jsx
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/util/siteMapConstants.ts
Labels: bug

#3591 LF-4573 The message “These animals will be archived and accessible for future reference” is displayed when removing animals
  packages/webapp/public/locales/en/translation.json
Labels: bug, enhancement

#3595 LF-4615 No actions are triggered once the user clicks on the "Clear All" button during the creation of the "Movement" task
  packages/webapp/src/components/Task/MovementTask/styles.module.scss
Labels: bug

#3598 LF-4606 “Click to upload link” should not display or should “look” disabled if not in editing mode [Duplicate - See Usability section]
  packages/webapp/src/components/Animals/DetailCards/Other.tsx
Labels: bug

#3601 LF-4570: Farm image preview is broken on beta
  packages/webapp/src/components/ImagePicker/index.tsx
  packages/webapp/src/components/ImagePicker/styles.module.scss
  packages/webapp/src/components/Profile/Farm/index.jsx
Labels: bug

#3603 LF-4610 fix location styling
  packages/webapp/src/components/Animals/AnimalSingleViewHeader/styles.module.scss
  packages/webapp/src/components/Form/ReactSelect/styles.ts
Labels: bug

#3599 LF-4593 fix animals filter
  packages/webapp/src/containers/Animals/AnimalsFilter/index.tsx
Labels: bug

#3596 LF-4575 fix date range filter
  packages/webapp/src/components/Filter/FilterDateRange/index.jsx
Labels: bug

#3607 LF-4612b Accidental click outside checkbox goes to details view and loses check progress
  packages/webapp/src/components/Table/Cell/styles.module.scss
  packages/webapp/src/components/Table/styles.module.scss
Labels: bug

#3605 LF-4611 Add no animal locations modal
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Modals/NoAnimalLocationsModal/index.jsx
  packages/webapp/src/components/Modals/NoAnimalLocationsModal/styles.module.scss
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
  packages/webapp/src/containers/Task/TaskTypeSelection/index.jsx
  packages/webapp/src/containers/locationSlice.js
Labels: new translations

#3612 LF-4612c Fix margin on icons without checkbox
  packages/webapp/src/components/Table/Cell/CellTypes/IconText.tsx
  packages/webapp/src/components/Table/Cell/styles.module.scss
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/Inventory/styles.module.scss
Labels: bug
