Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-08, with the labels that each got.

#3370 LF-4166 (1): Implement end to end animal creation flow
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Animals/Inventory/index.tsx
  packages/webapp/src/components/Form/FormNavigationButtons/index.tsx
  packages/webapp/src/components/Form/MultiStepForm/index.jsx
  packages/webapp/src/containers/Animals/AddAnimalBasics/index.tsx
  packages/webapp/src/containers/Animals/AddAnimalDetails/index.tsx
  packages/webapp/src/containers/Animals/AddAnimalSummary/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/routes/AnimalsRoutes.jsx
  packages/webapp/src/stories/FormNavigationButtons/FormNavigationButtons.stories.tsx
  packages/webapp/src/stories/MultiStepForm/MultiStepForm.stories.tsx
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement

#3285 Automatically add JIRA ticket number to commit messages
  .husky/commit-msg
  .husky/commit-msg.js
  lint-staged.config.js
  package.json
  tests/prepare-commit-msg.test.js
Labels: enhancement

#3372 LF-4163 Create (merge) animal basics container
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AddAnimalsFormCard.tsx
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
  packages/webapp/src/components/Animals/AddAnimalsFormCard/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalBasics/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalBasics/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalSummary/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/types.ts
  packages/webapp/src/stories/AddAnimalsFormCard/AddAnimalsFormCard.stories.tsx
  packages/webapp/src/util/animal.ts
Labels: enhancement

#3375 LF-4365 Upgrade Storybook to v8
  packages/webapp/.storybook/main.cjs
  packages/webapp/.storybook/preview.jsx
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/stories/Animals/Details/Origin.stories.tsx
  packages/webapp/src/stories/CardsCarrousel/CardsCarrousel.stories.jsx
  packages/webapp/src/stories/DateRangeSelector/DateRangeSelector.stories.jsx
  packages/webapp/src/stories/ExpandableItem/ExpandableItem.stories.jsx
  packages/webapp/src/stories/Filters/FilterGroup.stories.jsx
  packages/webapp/src/stories/Form/DaysOfWeekSelect/DaysOfWeekSelect.stories.jsx
  packages/webapp/src/stories/Form/Input/Input.stories.jsx
  packages/webapp/src/stories/Form/NumberInput/NumberInput.stories.tsx
  packages/webapp/src/stories/Modal/FileSizeExceedModal.stories.jsx
  packages/webapp/src/stories/Modal/WaterUsageCalculatorModal.stories.jsx
  packages/webapp/src/stories/Pages/FullYearCalendar/FullMonthCalendar.stories.jsx
  packages/webapp/src/stories/Pages/Intro/RequestCertifier/RequestCertifier.stories.jsx
  packages/webapp/src/stories/Pages/Intro/SetCertificationSummary/SetCertificationSummary.stories.jsx
  packages/webapp/src/stories/Pages/ManagementPlan/CompleteManagementPlan.stories.jsx
  packages/webapp/src/stories/Pages/Profile/EditUser.stories.jsx
  packages/webapp/src/stories/Pages/Task/TaskDetail/TaskDetail.stories.jsx
  packages/webapp/src/stories/Pages/Tasks/HarvestUses.stories.jsx
  packages/webapp/src/stories/Pages/Tasks/TaskReadOnly.stories.jsx
  packages/webapp/src/stories/Pages/ViewCertification/ViewCertification.stories.jsx
  packages/webapp/src/stories/SurveyExport/SurveyExport.stories.jsx
  packages/webapp/src/stories/Tile/Tiles.stories.jsx
  packages/webapp/src/stories/assets/codeSplitting/mainBundleCurrency.png
  packages/webapp/src/stories/assets/codeSplitting/mainBundleWithoutCurrency.png
  packages/webapp/src/stories/assets/redux/cropTable.png
  packages/webapp/src/stories/assets/refactoring-imgs/harvest-log-pure1.png
  packages/webapp/src/stories/assets/refactoring-imgs/harvest-log-pure2.png
  packages/webapp/src/stories/assets/refactoring-imgs/harvest-log-smart1.png
  packages/webapp/src/stories/assets/refactoring-imgs/harvest-log-smart2.png
  packages/webapp/src/stories/assets/techStackSummary/locationSchema.png
  packages/webapp/src/stories/docs/DocCard.jsx
  packages/webapp/src/stories/docs/DocLink.jsx
  packages/webapp/src/stories/docs/bugs.stories.mdx
  packages/webapp/src/stories/docs/codeSplitting.stories.mdx
  packages/webapp/src/stories/docs/componentsToDeprecate.stories.mdx
  packages/webapp/src/stories/docs/refactoringGiude.stories.mdx
  packages/webapp/src/stories/docs/storybook.stories.mdx
  packages/webapp/src/stories/docs/teckStackNavigation.jsx
  packages/webapp/src/stories/docs/tutorial/RestAPIendpoint .stories.mdx
  packages/webapp/src/stories/docs/tutorial/backendUnitTest.stories.mdx
  packages/webapp/src/stories/docs/tutorial/container.stories.mdx
  packages/webapp/src/stories/docs/tutorial/controller.stories.mdx
  packages/webapp/src/stories/docs/tutorial/forms.stories.mdx
  packages/webapp/src/stories/docs/tutorial/middleware.stories.mdx
  packages/webapp/src/stories/docs/tutorial/migrationAndObjectionModel.stories.mdx
  packages/webapp/src/stories/docs/tutorial/reduxAndReduxSaga.stories.mdx
  packages/webapp/src/stories/docs/tutorial/storybook.stories.mdx
  packages/webapp/src/stories/docs/tutorial/techStackSummary.stories.mdx
  packages/webapp/src/test-utils/storybook/unit.jsx
Labels: bug, enhancement

#3377 LF-4166 (2): [Layout] Implement end to end animal creation flow
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Form/MultiStepForm/WithPageTitle.tsx
  packages/webapp/src/components/Form/MultiStepForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/Form/MultiStepForm/index.jsx
  packages/webapp/src/components/Form/MultiStepForm/styles.module.scss
  packages/webapp/src/components/Navigation/useSectionHeaders.tsx
  packages/webapp/src/components/StepperProgressBar/index.tsx
  packages/webapp/src/components/StepperProgressBar/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/stories/StepperProgressBar/StepperProgressBar.stories.tsx
Labels: enhancement

#3280 LF-3951: Show water calculator with wild crops
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
  packages/webapp/src/components/Task/PureIrrigationTask/styles.module.scss
Labels: bug

#3394 LF-4164 Import from and install types for lodash-es instead of lodash
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts
Labels: bug

#3388 LF-4163: Animal basics layout adjustment
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Animals/AddAnimalsFormCard/styles.module.scss
  packages/webapp/src/components/Animals/FixedHeaderContainer/index.tsx
  packages/webapp/src/components/Animals/FixedHeaderContainer/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalBasics/styles.module.scss
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/styles.module.scss
Labels: enhancement

#3393 Image picker update
  packages/webapp/src/components/Animals/DetailCards/Other.tsx
  packages/webapp/src/components/ImagePicker/index.tsx
  packages/webapp/src/components/ImagePicker/useImagePickerUpload.tsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
  packages/webapp/src/containers/ImagePickerWrapper/saga.js
  packages/webapp/src/stories/Animals/Details/AnimalDetails.stories.tsx
  packages/webapp/src/stories/Animals/Details/BatchDetails.stories.tsx
  packages/webapp/src/stories/Animals/Details/Other.stories.tsx
  packages/webapp/src/stories/Animals/Details/mockData.ts
Labels: enhancement

#3391 Fix default_type_id type in animal uses API
  packages/api/src/models/animalUseModel.js
  packages/api/tests/animal_use.test.js
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
  packages/webapp/src/store/api/types/index.ts
Labels: bug

#3382 LF-4165: Create animal creation summary container
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Animals/AddAnimalsSummaryCard/IconSummary/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsSummaryCard/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsSummaryCard/types.ts
  packages/webapp/src/components/Form/MultiStepForm/index.jsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalSummary/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/utils.ts
  packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
  packages/webapp/src/stories/AddAnimalsSummaryCard/AddAnimalsSummaryCard.stories.tsx
  packages/webapp/src/stories/AddAnimalsSummaryCard/IconSummary/IconSummary.stories.tsx
  packages/webapp/src/tests/animalUtils.test.js
Labels: enhancement

#3398 LF-4397 Adjustments on add animals
  packages/api/db/migration/20240828191003_add_brought_in_date_birth_date_and_origin_id_to_animal_batch_table.js
  packages/api/src/middleware/checkAnimalEntities.js
  packages/api/src/models/animalBatchModel.js
  packages/api/tests/animal_batch.test.js
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/components/Animals/DetailCards/Origin.tsx
  packages/webapp/src/components/Animals/DetailCards/Other.tsx
  packages/webapp/src/components/Animals/DetailCards/Unique.tsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts
  packages/webapp/src/containers/Animals/AddAnimals/types.ts
  packages/webapp/src/stories/Animals/Details/mockData.ts
Labels: bug, enhancement
