Repository LiteFarmOrg/LiteFarm, pull requests merged in 2024-05, with the labels that each got.

#3192 LF-4158: Create animal creation details cards for animal
  packages/webapp/public/locales/en/animal.json
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/animal.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/animal.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/animal.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/components/Animals/AddAnimalsDetails/General.tsx
  packages/webapp/src/components/Animals/AddAnimalsDetails/Origin.tsx
  packages/webapp/src/components/Animals/AddAnimalsDetails/Other.tsx
  packages/webapp/src/components/Animals/AddAnimalsDetails/Unique.tsx
  packages/webapp/src/components/Animals/AddAnimalsDetails/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsDetails/styles.module.scss
  packages/webapp/src/components/Animals/AddAnimalsDetails/type.ts
  packages/webapp/src/components/Form/FilePickerWrapper/index.tsx
  packages/webapp/src/components/Form/Input/index.jsx
  packages/webapp/src/components/ImagePicker/index.tsx
  packages/webapp/src/components/ImagePicker/styles.module.scss
  packages/webapp/src/containers/Animals/types.ts
  packages/webapp/src/stories/Animals/Details/AnimalDetails.stories.tsx
  packages/webapp/src/stories/Animals/Details/General.stories.tsx
  packages/webapp/src/stories/Animals/Details/Origin.stories.tsx
  packages/webapp/src/stories/Animals/Details/Other.stories.tsx
  packages/webapp/src/stories/Animals/Details/Unique.stories.tsx
  packages/webapp/src/stories/Animals/Details/mockData.js
  packages/webapp/src/stories/ImagePicker/ImagePicker.stories.tsx
Labels: enhancement

#3200 LF-4215 Write migration to add columns to product table and create update APIs
  packages/api/db/migration/20240425225219_add_npk_and_update_permissions_on_product.js
  packages/api/src/controllers/productController.js
  packages/api/src/middleware/acl/hasFarmAccess.js
  packages/api/src/middleware/validation/checkProductValidity.js
  packages/api/src/models/productModel.js
  packages/api/src/routes/productRoute.js
  packages/api/tests/product.test.js
Labels: enhancement

#3203 LF-4217: Create component for product section buttons
  packages/webapp/src/components/Form/InFormButtons/index.tsx
  packages/webapp/src/components/Form/InFormButtons/styles.module.scss
  packages/webapp/src/stories/InFormButtons/InFormButtons.stories.tsx
Labels: enhancement

#3207 Fix some typos
  README.md
Labels: documentation

#3202 LF-4218: Create component for composition selects
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/public/locales/es/common.json
  packages/webapp/public/locales/es/translation.json
  packages/webapp/public/locales/fr/common.json
  packages/webapp/public/locales/fr/translation.json
  packages/webapp/public/locales/pt/common.json
  packages/webapp/public/locales/pt/translation.json
  packages/webapp/src/assets/images/ratio-option.svg
  packages/webapp/src/assets/mixin.scss
  packages/webapp/src/components/Form/CompositionInputs/NumberInputWithSelect.tsx
  packages/webapp/src/components/Form/CompositionInputs/index.tsx
  packages/webapp/src/components/Form/CompositionInputs/styles.module.scss
  packages/webapp/src/components/Form/InputBase/InputBaseField/index.tsx
  packages/webapp/src/components/Form/InputBase/InputBaseField/styles.module.scss
  packages/webapp/src/components/Form/InputBase/index.tsx
  packages/webapp/src/components/Form/NumberInput/useNumberInput.ts
  packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
Labels: enhancement

#3209 LF 4199: Fix undefined date range filter on Tasks page
  packages/webapp/src/components/Filter/FilterDateRange/index.jsx
  packages/webapp/src/components/FilterPage/index.tsx
  packages/webapp/src/containers/Filter/Tasks/index.jsx
  packages/webapp/src/containers/Filter/types.ts
Labels: bug

#3210 LF 4232: Fix 400 error when the user goes back during the task creation process
  packages/webapp/src/containers/Task/TaskAssignment/index.jsx
Labels: bug
