Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-09, with the labels that each got.

#3873 LF-4942 "Failed to fetch harvest use types" error snackbar shows inappropriately
  packages/webapp/public/locales/en/message.json
  packages/webapp/src/containers/Task/saga.js
Labels: bug

#3857 LF-4812: Show button to re-trigger completion in read only task view
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Task/RevisionPrompt/index.tsx
  packages/webapp/src/components/Task/RevisionPrompt/styles.module.scss
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
Labels: enhancement, new translations

#3875 LF-4947: Animals page and create task page display error screen when user is offline
  packages/webapp/src/containers/Animals/Inventory/KPI/index.tsx
  packages/webapp/src/containers/Animals/Inventory/useAnimalsExist.tsx
Labels: bug

#3858 LF-4814: Pre-fill task completion flow forms with previous values
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/Quantity.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
Labels: enhancement

#3877 LF-4958 "I prefer not to say" Option Is Preselected by Default When Starting Task Completion
  packages/webapp/src/components/Task/TaskComplete/index.jsx
Labels: bug

#3878 LF-4957 Rating, Notes, and Time Spent Not Persisted During Task Re-Completion
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
Labels: bug

#3872 Routes cleanup
  packages/webapp/src/routes/Onboarding.jsx
  packages/webapp/src/routes/index.jsx
Labels: bug
