Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-05, with the labels that each got.

#3744 LF-4790: IP detail KPI
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/clock-stopwatch.svg
  packages/webapp/src/assets/images/irrigation/pivot-icon.svg
  packages/webapp/src/assets/images/weather/droplets.svg
  packages/webapp/src/assets/images/weather/thermometer-warm.svg
  packages/webapp/src/assets/images/weather/wind.svg
  packages/webapp/src/components/IrrigationPrescription/types.ts
  packages/webapp/src/components/IrrigationPrescriptionKPI/index.tsx
  packages/webapp/src/components/IrrigationPrescriptionKPI/styles.module.scss
  packages/webapp/src/components/IrrigationPrescriptionKPI/util.tsx
  packages/webapp/src/components/Tile/DescriptionList/index.tsx
  packages/webapp/src/components/Tile/DescriptionList/styles.module.scss
  packages/webapp/src/components/WeatherKPI/index.tsx
  packages/webapp/src/containers/IrrigationPrescription/index.tsx
  packages/webapp/src/containers/SensorReadings/v2/LatestReadings/index.tsx
  packages/webapp/src/containers/SensorReadings/v2/LatestReadings/utils.tsx
  packages/webapp/src/containers/SensorReadings/v2/styles.module.scss
  packages/webapp/src/stories/Tile/DescriptionList/DescriptionList.stories.tsx
  packages/webapp/src/stories/Tile/DescriptionList/mockData.tsx
  packages/webapp/src/stories/Tile/DescriptionList/styles.module.scss
  packages/webapp/src/stories/WeatherKPI/WeatherKPI.stories.tsx
  packages/webapp/src/stories/WeatherKPI/mockData.tsx
Labels: enhancement, new translations

#3752 LF-4770(2): Display flow to approve an IP and create a task from it
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Form/FormNavigationButtons/index.tsx
  packages/webapp/src/components/IrrigationPrescription/types.ts
  packages/webapp/src/containers/IrrigationPrescription/index.tsx
  packages/webapp/src/containers/IrrigationPrescription/styles.module.scss
  packages/webapp/src/containers/IrrigationPrescription/useApproveIrrigationPrescription.ts
  packages/webapp/src/containers/slice/taskSlice/irrigationTaskSlice.js
  packages/webapp/src/routes/index.jsx
  packages/webapp/src/stories/FormNavigationButtons/FormNavigationButtons.stories.tsx
Labels: enhancement, new translations

#3758 LF-4770 (3): Display flow to approve an IP and create a task from it
  packages/webapp/public/locales/en/common.json
  packages/webapp/src/components/ChooseFarm/index.jsx
  packages/webapp/src/components/CreateUserAccount/index.jsx
  packages/webapp/src/components/Logs/HarvestAllocation/index.jsx
  packages/webapp/src/components/Signup/EnterPasswordPage/index.jsx
  packages/webapp/src/containers/ErrorHandler/UnknownRecord/UnknownRecord.jsx
  packages/webapp/src/containers/IrrigationPrescription/index.tsx
Labels: new translations

#3754 LF-4769 Modify task creation to accept IP id and update status on Ensemble
  packages/api/src/controllers/taskController.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/routes/taskRoute.js
  packages/api/src/services/task.ts
  packages/api/src/util/ensembleService.ts
  packages/api/src/util/task.js
  packages/api/tests/mock.factories.js
  packages/api/tests/task.test.js
Labels: enhancement

#3763 LF-4785: Fix crash when long pressing ESci sensor icon
  packages/webapp/src/components/Map/PreviewPopup/index.jsx
  packages/webapp/src/containers/Map/LocationSelectionModal/index.jsx
Labels: bug

#3765 LF-4773: Cancel and back buttons are not working on the add sensors flow
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/containers/AddSensors/index.tsx
Labels: bug

#3764 LF-4707: Clear error icon position is off on input without a label
  packages/webapp/src/components/Form/Input/index.jsx
  packages/webapp/src/components/Form/Input/input.module.scss
  packages/webapp/src/stories/Form/Input/Input.stories.jsx
Labels: bug

#3762 LF-4771 Create notification when new IP is available
  packages/api/src/controllers/timeNotificationController.js
  packages/api/src/jobs/notifications/index.js
  packages/api/src/middleware/validation/checkTask.js
  packages/api/src/routes/timeNotificationRoute.js
  packages/api/src/util/ensembleService.ts
  packages/api/tests/task.test.js
  packages/api/tests/timeNotification.test.js
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/irrigation/notification-pivot-icon.svg
  packages/webapp/src/components/util/getNotificationTypeIcon.js
  packages/webapp/src/containers/IrrigationPrescription/index.tsx
Labels: enhancement, new translations

#3766 LF-4781 Add cronjob to request IPs from Ensemble daily
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/jobs/index.js
  packages/api/src/jobs/requests/index.js
  packages/api/src/middleware/acl/checkJwt.js
  packages/api/src/middleware/acl/checkSchedulerPermission.js
  packages/api/src/middleware/acl/hasTimeNotificationsAccess.js
  packages/api/src/routes/farmRoute.js
  packages/api/src/routes/irrigationPrescriptionRequestRoute.ts
  packages/api/src/routes/timeNotificationRoute.js
Labels: enhancement

#3771 LF-4828 Add database migration to support new location type
  packages/api/db/migration/20250514175826_create_soil_sample_location.js
Labels: enhancement

#3760 LF-4818: Fix get task type tasks success reducers
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/containers/slice/taskSlice/animalMovementTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/cleaningTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/fieldWorkTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/harvestTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/irrigationTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/pestControlTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/plantTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/soilAmendmentTaskSlice.js
  packages/webapp/src/containers/slice/taskSlice/transplantTaskSlice.js
Labels: bug

#3773 LF-4829 Create soil sample endpoints and update location controller
  packages/api/src/controllers/locationController.js
  packages/api/src/middleware/validation/location.js
  packages/api/src/models/figureModel.js
  packages/api/src/models/locationModel.js
  packages/api/src/models/soilSampleLocationModel.js
  packages/api/src/routes/locationRoute.js
  packages/api/tests/location.test.js
  packages/api/tests/testEnvironment.js
Labels: enhancement

#3775 LF-4831 UI flow to view and edit soil sample location
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SoilSampleLocationDetailForm/EditSoilSampleLocation.jsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SoilSampleLocationDetailForm/saga.js
  packages/webapp/src/routes/SoilSampleLocationDetailsRoutes.jsx
  packages/webapp/src/routes/index.jsx
Labels: enhancement

#3779 Lf 4772 display ip details and file on task detail view
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/components/Task/TaskReadOnly/styles.module.scss
  packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
  packages/webapp/src/stories/IrrigationPrescription/mockData.tsx
  packages/webapp/src/util/geoUtils.ts
Labels: new translations

#3776 LF-4832 Add database migration to support new task type
  packages/api/db/migration/20250520185926_create_soil_sample_task_table.js
Labels: enhancement

#3777 LF-4833 Add endpoint to create a soil sampling task
  packages/api/src/controllers/taskController.js
  packages/api/src/middleware/validation/task.js
  packages/api/src/models/soilSampleTaskModel.js
  packages/api/src/models/taskModel.js
  packages/api/src/routes/taskRoute.js
  packages/api/tests/mock.factories.js
  packages/api/tests/task.test.js
  packages/api/tests/testEnvironment.js
Labels: enhancement

#3780 Lf 4840 new task type card form flow
  packages/webapp/public/locales/en/task.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Modals/NoSoilSampleLocationsModal/index.jsx
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
  packages/webapp/src/components/Task/getSupportedTaskTypesSet.js
  packages/webapp/src/containers/Task/TaskLocations/index.jsx
  packages/webapp/src/containers/Task/TaskTypeSelection/index.jsx
Labels: new translations
