Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-01, with the labels that each got.

#3641 Fix failing frontend GitHub workflows after 3.7.3 patch and backport
  .github/workflows/lint_translation_files.yml
  .github/workflows/webapp_unit_tests.yml
  packages/webapp/pnpm-lock.yaml
Labels: bug

#3654 Remove server.js CORS for development environment
  packages/api/src/server.js
Labels: bug

#3653 LF-4626 Automatically detect field for sensor array
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/hooks/useFarmAreasContainingPoint.ts
  packages/webapp/src/util/geoUtils.ts
Labels: enhancement

#3655 LF-4690 Create POST endpoint to create an Ensemble addon
  packages/api/src/controllers/farmAddonController.js
  packages/api/src/middleware/validation/checkFarmAddon.js
  packages/api/src/models/addonPartnerModel.js
  packages/api/src/models/farmAddonModel.js
  packages/api/src/routes/farmAddonRoute.js
  packages/api/src/routes/sensorRoute.js
  packages/api/src/server.js
  packages/api/src/util/ensemble.js
Labels: enhancement

#3659 LF-4631 (1): Implement sensor addition UI flow
  packages/webapp/public/locales/en/common.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/App.jsx
  packages/webapp/src/components/Form/ContextForm/HeaderWithBackAndClose.tsx
  packages/webapp/src/components/Form/ContextForm/Loading.tsx
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/Form/ContextForm/styles.module.scss
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/PostSensor.tsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/styles.module.scss
  packages/webapp/src/routes/index.jsx
  packages/webapp/src/stories/ContextForm/ContextForm.stories.tsx
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement, new translations

#3665 LF-4695 Create GET endpoint to fetch list of Ensemble devices
  packages/api/src/controllers/farmAddonController.js
  packages/api/src/controllers/sensorController.js
  packages/api/src/models/farmAddonModel.js
  packages/api/src/routes/sensorRoute.js
  packages/api/src/util/ensemble.js
  packages/webapp/src/components/LocationDetailLayout/PointDetails/Sensor/index.jsx
  packages/webapp/src/components/Map/PreviewPopup/index.jsx
  packages/webapp/src/components/Map/SelectionHandler/index.jsx
  packages/webapp/src/containers/Home/index.jsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/EditSensor.jsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/index.jsx
  packages/webapp/src/containers/SensorReadings/index.jsx
  packages/webapp/src/containers/locationSlice.js
  packages/webapp/src/containers/saga.js
  packages/webapp/src/store/api/apiSlice.ts
  packages/webapp/src/store/api/selectors/sensorSelectors.ts
  packages/webapp/src/store/api/types/index.ts
Labels: enhancement

#3673 LF-4690b Fix Ensemble API call bug on token refresh and return descriptive errors on API call failure
  packages/api/src/controllers/farmAddonController.js
  packages/api/src/controllers/sensorController.js
  packages/api/src/util/ensemble.js
Labels: bug
