Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-02, with the labels that each got.

#3680 LF-4718 (2) Repair Deployment of Webapp
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
  packages/webapp/src/components/Expandable/useExpandableItem.ts
Labels: bug

#3681 TypeScript cleanup -- hookFormValidationUtils.ts and ts-expect-error
  packages/webapp/src/components/Animals/AddAnimalsDetails/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AddAnimalsFormCard.tsx
  packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
  packages/webapp/src/components/Animals/DetailCards/General.tsx
  packages/webapp/src/components/Animals/DetailCards/Origin.tsx
  packages/webapp/src/components/Animals/DetailCards/Other.tsx
  packages/webapp/src/components/Animals/DetailCards/Unique.tsx
  packages/webapp/src/components/Animals/Inventory/index.tsx
  packages/webapp/src/components/Animals/RemoveAnimalsModal/index.tsx
  packages/webapp/src/components/Form/ContextForm/WithPageTitle.tsx
  packages/webapp/src/components/Form/ReactSelect/CreatableSelect.tsx
  packages/webapp/src/components/Form/hookformValidationUtils.ts
  packages/webapp/src/components/ImagePicker/useImagePickerUpload.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/index.tsx
  packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/useQuantityApplicationRate.ts
  packages/webapp/src/components/Task/MovementTask/index.tsx
  packages/webapp/src/components/Task/SoilAmendmentTask/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
  packages/webapp/src/containers/Animals/Inventory/index.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/stories/AddAnimalsSummaryCard/AddAnimalsSummaryCard.stories.tsx
Labels: enhancement

#3682 LF-4722 Backend container crashes due to missing server.js file
  packages/api/package.json
  packages/api/prod.Dockerfile
Labels: bug

#3683 LF-4722b Fix start:prod path to match container structure
  packages/api/package.json
Labels: bug

#3676 LF-4711 Make the Online/Offline badge and make it into a Table Cell Kind
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/status-indicator-dot.svg
  packages/webapp/src/components/HoverPillOverflowList/index.tsx
  packages/webapp/src/components/HoverPillOverflowList/styles.module.scss
  packages/webapp/src/components/StatusIndicatorPill/index.tsx
  packages/webapp/src/components/StatusIndicatorPill/styles.module.scss
  packages/webapp/src/components/Table/Cell/CellTypes/HoverPillOverflow.tsx
  packages/webapp/src/components/Table/Cell/index.tsx
  packages/webapp/src/components/Table/Cell/styles.module.scss
  packages/webapp/src/components/Table/types.ts
  packages/webapp/src/stories/HoverPillOverflowList/HoverPillOverflowList.stories.tsx
  packages/webapp/src/stories/HoverPillOverflowList/styles.module.scss
  packages/webapp/src/stories/StatusIndicatorPill/StatusIndicatorPill.stories.tsx
  packages/webapp/src/stories/StatusIndicatorPill/styles.module.scss
  packages/webapp/src/stories/Table/TableCells.stories.jsx
Labels: enhancement, new translations

#3688 LF-4732: White screen appears when clicking three dots button on animal profile page
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/Menu/MeatballsMenu/index.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
Labels: bug

#3689 LF-4734 It is not possible to continue animal creation flow without specifying animal breed
  packages/webapp/src/components/Form/hookformValidationUtils.ts
Labels: bug

#3685 LF-4693 Display existing Ensemble addon
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/link-broken.svg
  packages/webapp/src/components/Form/ContextForm/index.tsx
  packages/webapp/src/components/Profile/Addons/index.tsx
  packages/webapp/src/components/Profile/Addons/styles.module.scss
  packages/webapp/src/components/Profile/Farm/index.jsx
  packages/webapp/src/components/Sensor/v2/Partners.tsx
  packages/webapp/src/components/Sensor/v2/styles.module.scss
  packages/webapp/src/components/Table/TableV2.jsx
  packages/webapp/src/components/Table/types.ts
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/Partners.tsx
  packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/PostSensor.tsx
  packages/webapp/src/containers/Profile/Farm/Addons/index.tsx
  packages/webapp/src/containers/saga.js
  packages/webapp/src/store/api/apiSlice.ts
  packages/webapp/src/types/index.ts
Labels: enhancement, new translations

#3690 Resolve eslint backend precommit error
  packages/api/eslint.config.js
  packages/api/jest-global-setup.ts
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/controllers/sensorController.js
Labels: bug

#3693 Reorganize and finalize ensemble addon UI
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/AddSensors/Partners.tsx
  packages/webapp/src/components/AddSensors/styles.module.scss
  packages/webapp/src/components/Animals/AddAnimalsForm/AnimalFormHeaderItem/index.tsx
  packages/webapp/src/components/Animals/AddAnimalsForm/AnimalFormHeaderItem/styles.module.scss
  packages/webapp/src/components/Expandable/InlineRemove.tsx
  packages/webapp/src/components/Expandable/MainContent.tsx
  packages/webapp/src/components/Expandable/styles.module.scss
  packages/webapp/src/components/Profile/Addons/index.tsx
  packages/webapp/src/components/Sensor/v2/SensorTable/index.tsx
  packages/webapp/src/containers/AddSensors/Partners.tsx
  packages/webapp/src/containers/AddSensors/constants.ts
  packages/webapp/src/containers/AddSensors/index.tsx
  packages/webapp/src/containers/AddSensors/styles.module.scss
  packages/webapp/src/containers/AddSensors/types.ts
  packages/webapp/src/containers/Map/index.jsx
  packages/webapp/src/containers/Profile/Farm/Addons/index.tsx
  packages/webapp/src/containers/SensorList/index.tsx
  packages/webapp/src/containers/SensorList/useGroupedSensors.ts
  packages/webapp/src/routes/index.jsx
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement, new translations

#3695 ESci Sensor List KPI and string adjustments
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/OverviewStats/styles.module.scss
  packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
  packages/webapp/src/stories/OverviewStats/OverviewStats.stories.tsx
  packages/webapp/src/util/index.js
Labels: enhancement

#3696 LF-4701 Call DELETE endpoint when clicking disconnect from Farm Addon
  packages/api/src/controllers/farmAddonController.js
  packages/webapp/public/locales/en/message.json
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/containers/AddSensors/Partners.tsx
  packages/webapp/src/containers/Profile/Farm/Addons/index.tsx
  packages/webapp/src/store/api/apiSlice.ts
  packages/webapp/src/store/api/types/index.ts
Labels: enhancement

#3700 Farm Addon & Partner visual adjustments
  packages/webapp/src/components/Form/Button/button.module.scss
  packages/webapp/src/containers/AddSensors/Partners.tsx
Labels: bug
