Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-03, with the labels that each got.

#3703 LF-4719 Update Cypress node version
  .github/workflows/cypress_tests.yml
Labels: bug

#3704 LF-4749 Bump Ubuntu actions runner to 24.04
  .github/workflows/automated_tests.yml
  .github/workflows/beta-export-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/lint_translation_files.yml
  .github/workflows/rollout.yml
Labels: dependencies

#3706 Adjust Ensemble sensor GET to handle missing paramter_types
  packages/api/src/util/ensemble.js
Labels: bug

#3708 LF-4746(1) FinancesDateRangeSelector minor refactors and bugfixes
  packages/webapp/src/components/DateRangeSelector/constants.jsx
  packages/webapp/src/components/DateRangeSelector/index.jsx
  packages/webapp/src/components/DateRangeSelector/types.ts
  packages/webapp/src/components/Finances/DateRangeSelector/index.tsx
  packages/webapp/src/components/Finances/DateRangeSelector/useFinancesDateRange.ts
  packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
  packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx
  packages/webapp/src/containers/Finances/Labour/index.jsx
  packages/webapp/src/containers/Finances/OtherExpense/index.jsx
  packages/webapp/src/containers/Finances/Report/index.jsx
  packages/webapp/src/containers/Finances/actions.js
  packages/webapp/src/containers/Finances/constants.js
  packages/webapp/src/containers/Finances/index.jsx
  packages/webapp/src/containers/Finances/reducer.js
  packages/webapp/src/containers/Finances/saga.js
  packages/webapp/src/containers/saga.js
  packages/webapp/src/stories/DateRangeSelector/DateRangeSelector.stories.jsx
  packages/webapp/src/tests/dateRange.test.js
  packages/webapp/src/util/dateRange.js
Labels: bug, enhancement

#3710 LF-4704 Update cancel flow modal
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/AddCropVariety/ComplianceInfo/index.jsx
  packages/webapp/src/components/AddCropVariety/index.jsx
  packages/webapp/src/components/AddNewCrop/index.jsx
  packages/webapp/src/components/CertificationReportingPeriod/index.jsx
  packages/webapp/src/components/CertificationSurvey/index.jsx
  packages/webapp/src/components/Crop/BedPlan/PureBedPlan.jsx
  packages/webapp/src/components/Crop/BedPlan/PurePlanGuidance.jsx
  packages/webapp/src/components/Crop/BroadcastPlan/index.jsx
  packages/webapp/src/components/Crop/ManagementPlanName/index.jsx
  packages/webapp/src/components/Crop/PlantInContainer/index.jsx
  packages/webapp/src/components/Crop/PlantedAlready/index.jsx
  packages/webapp/src/components/Crop/PlantingDate/NextHarvest.jsx
  packages/webapp/src/components/Crop/PlantingDate/PurePlantingDate.jsx
  packages/webapp/src/components/Crop/PlantingLocation/index.jsx
  packages/webapp/src/components/Crop/PlantingMethod/PureManagementPlanPlantingMethod.jsx
  packages/webapp/src/components/Crop/RowMethod/index.jsx
  packages/webapp/src/components/Crop/Transplant/index.jsx
  packages/webapp/src/components/Documents/Add/index.jsx
  packages/webapp/src/components/Finances/AddExpense/index.jsx
  packages/webapp/src/components/Finances/PureFinanceTypeSelection/index.jsx
  packages/webapp/src/components/Form/ContextForm/WithPageTitle.tsx
  packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
  packages/webapp/src/components/LocationDetailLayout/LocationPageHeader.jsx
  packages/webapp/src/components/Modals/CancelFlowModal/index.jsx
  packages/webapp/src/components/Modals/CancelFlowModal/styles.module.scss
  packages/webapp/src/components/PageTitle/CancelButton.jsx
  packages/webapp/src/components/PageTitle/MultiStepPageTitle/index.jsx
  packages/webapp/src/components/PageTitle/v2/index.jsx
  packages/webapp/src/components/RepeatCropPlan/Confirmation.jsx
  packages/webapp/src/components/RepeatCropPlan/index.jsx
  packages/webapp/src/components/Task/PureTaskAssignment/index.jsx
  packages/webapp/src/components/Task/PureTaskCrops/index.jsx
  packages/webapp/src/components/Task/PureTaskDetails/index.jsx
  packages/webapp/src/components/Task/PureTaskPlantingMethod/PureManagementPlanPlantingMethod.jsx
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
  packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
  packages/webapp/src/components/Task/TaskComplete/HarvestComplete/Quantity.jsx
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
  packages/webapp/src/components/Task/TaskDate/index.jsx
  packages/webapp/src/components/Task/TaskLocations/index.jsx
  packages/webapp/src/containers/AddSensors/index.tsx
  packages/webapp/src/containers/Animals/AddAnimals/index.tsx
  packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
  packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
  packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
  packages/webapp/src/stories/ContextForm/ContextForm.stories.tsx
  packages/webapp/src/stories/Modal/CancelFlowModal.stories.jsx
  packages/webapp/src/stories/Modal/ModalComponentV2.stories.jsx
  packages/webapp/src/stories/Pages/Finance/PureFinanceTypeSelection.stories.jsx
Labels: enhancement, new translations

#3711 LF-4561: Task creation date mismatch between creation and listing page
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/main.jsx
  packages/webapp/src/polyfillDateTimeFormat.ts
Labels: bug

#3712 LF-4754 Add all new strings related to Field Technology to integration
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/AddSensors/Partners.tsx
Labels: new translations

#3698 LF-4698 Create endpoints to get sensor array readings from Ensemble
  packages/api/src/controllers/sensorController.js
  packages/api/src/middleware/validation/checkSensorReadingsQuery.ts
  packages/api/src/routes/sensorRoute.js
  packages/api/src/util/ensemble.js
  packages/api/src/util/util.js
  packages/api/src/util/validation.ts
  packages/api/tests/mock.factories.js
  packages/api/tests/sensor.test.ts
  packages/api/tests/testEnvironment.js
  packages/api/tests/utils/sensorMockData.ts
  packages/webapp/src/store/api/apiSlice.ts
  packages/webapp/src/store/api/types/index.ts
Labels: enhancement

#3713 LF-4756: Add all new strings related to sensor readings to integration
  packages/webapp/public/locales/en/translation.json
Labels: enhancement, new translations

#3709 LF-4746 (2) Create date range filter for sensor readings
  packages/webapp/src/components/DateRangeSelector/DateRangeInput.jsx
  packages/webapp/src/components/DateRangeSelector/index.tsx
  packages/webapp/src/components/DateRangeSelector/styles.module.scss
  packages/webapp/src/components/DateRangeSelector/types.ts
  packages/webapp/src/components/DateRangeSelector/useDateRange.ts
  packages/webapp/src/components/Finances/DateRangeSelector/index.tsx
  packages/webapp/src/components/Finances/DateRangeSelector/styles.module.scss
  packages/webapp/src/components/Finances/DateRangeSelector/useFinancesDateRange.ts
  packages/webapp/src/components/Sensor/v2/SensorsDateRange/index.tsx
  packages/webapp/src/components/Sensor/v2/SensorsDateRange/useSensorsDateRange.tsx
  packages/webapp/src/stories/DateRangeInput/DateRangeInput.stories.jsx
Labels: enhancement

#3719 LF-4652 Fix pnpm to exact version
  .github/workflows/chromatic.yml
  .github/workflows/cypress_tests.yml
  .github/workflows/lint_translation_files.yml
  .github/workflows/webapp_unit_tests.yml
  README.md
  packages/webapp/.npmrc
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/prod.Dockerfile
  packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
  packages/webapp/src/stories/Form/NumberInput/NumberInput.stories.tsx
Labels: bug, documentation, enhancement

#3721 LF-4724 Fix beta export server deploy
  beta-export-deploy.sh
Labels: bug

#3722 LF-4779 Repair Chromatic GitHub action workflow
  .github/workflows/chromatic.yml
Labels: bug

#3724 LF-4756(2): Strings for wind direction
  packages/webapp/public/locales/en/translation.json
Labels: new translations

#3714 LF-4699(1): Display sensor readings on the UI
  packages/webapp/src/assets/theme/index.tsx
  packages/webapp/src/components/Charts/LineChart.tsx
  packages/webapp/src/components/Charts/Tooltip.tsx
  packages/webapp/src/components/Charts/styles.module.scss
  packages/webapp/src/components/Charts/utils.ts
  packages/webapp/src/stories/Chart/LineChart.stories.tsx
  packages/webapp/src/stories/Chart/mockData.ts
  packages/webapp/src/tests/chartUtils.test.js
Labels: enhancement

#3715 LF-4627 [Nice to have] Implement Add to Map redesign
  packages/webapp/src/components/Drawer/index.tsx
  packages/webapp/src/components/Drawer/style.module.scss
  packages/webapp/src/components/Form/ContextForm/WithPageTitle.tsx
  packages/webapp/src/components/Map/Footer/index.jsx
  packages/webapp/src/components/MapDrawer/MapDrawerMenuItem.jsx
  packages/webapp/src/components/MapDrawer/index.jsx
  packages/webapp/src/components/MapDrawer/styles.module.scss
  packages/webapp/src/components/Navigation/SideMenu/index.jsx
  packages/webapp/src/components/PageTitle/CancelButton.jsx
  packages/webapp/src/components/PageTitle/MultiStepPageTitle/index.jsx
  packages/webapp/src/containers/FeedbackSurvey/index.jsx
  packages/webapp/src/containers/FeedbackSurvey/styles.module.scss
  packages/webapp/src/containers/Map/index.jsx
  packages/webapp/src/stories/Drawer/Drawer.stories.tsx
  packages/webapp/src/stories/Drawer/styles.module.scss
  packages/webapp/src/types/global.d.ts
Labels: enhancement
