Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-04, with the labels that each got.

#3735 Fix API tests error after axios upgrade: cannot use import statement outside a module
  packages/api/package-lock.json
  packages/api/package.json
Labels: bug

#3723 LF-4766 Create method to request IP from Ensemble
  packages/api/src/controllers/irrigationPrescriptionRequestController.ts
  packages/api/src/controllers/managementPlanController.js
  packages/api/src/models/addonPartnerModel.js
  packages/api/src/models/farmAddonModel.js
  packages/api/src/models/locationModel.js
  packages/api/src/models/managementPlanModel.js
  packages/api/src/routes/irrigationPrescriptionRequestRoute.ts
  packages/api/src/routes/managementPlanRoute.js
  packages/api/src/server.ts
  packages/api/src/util/ensemble.js
  packages/api/src/util/ensembleService.ts
  packages/api/src/util/ensembleService.types.ts
  packages/api/tests/irrigation_prescription_request.test.ts
  packages/api/tests/managementPlan.test.js
  packages/api/tests/sensor.test.ts
  packages/api/tests/utils/ensembleUtils.ts
  packages/api/tests/utils/testDataSetup.ts
Labels: enhancement

#3731 LF-4768 Display IP Detail (1) / Display IP on Map
  packages/webapp/src/assets/colors.scss
  packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionMapView.tsx
  packages/webapp/src/components/IrrigationPrescription/constants.ts
  packages/webapp/src/components/IrrigationPrescription/styles.module.scss
  packages/webapp/src/components/LocationPicker/LocationViewer.tsx
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/drawLocations.js
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.d.ts
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/types.ts
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Map/constants.js
  packages/webapp/src/containers/Map/mapStyles.js
  packages/webapp/src/containers/Map/styles.module.scss
  packages/webapp/src/stories/IrrigationPrescriptionMapView/IrrigationPrescriptionMapView.stories.tsx
  packages/webapp/src/stories/IrrigationPrescriptionMapView/mockData.tsx
  packages/webapp/src/stories/IrrigationPrescriptionMapView/styles.module.scss
Labels: enhancement

#3738 LF-4768 Display IP Detail (2) / Create <PureIrrigationPrescription /> component
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/dot.svg
  packages/webapp/src/components/Icons/icons.tsx
  packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionMapView.tsx
  packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionTable.tsx
  packages/webapp/src/components/IrrigationPrescription/index.tsx
  packages/webapp/src/components/IrrigationPrescription/styles.module.scss
  packages/webapp/src/components/IrrigationPrescription/types.ts
  packages/webapp/src/components/Table/Cell/CellTypes/IconText.tsx
  packages/webapp/src/stories/IrrigationPrescription/IrrigationPrescriptionMapView.stories.tsx
  packages/webapp/src/stories/IrrigationPrescription/PureIrrigationPrescription.stories.tsx
  packages/webapp/src/stories/IrrigationPrescription/mockData.tsx
  packages/webapp/src/stories/IrrigationPrescription/styles.module.scss
Labels: enhancement, new translations

#3742 LF-4797 Clean up Google maps event listeners added with `maps.event.addListener()`
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
  packages/webapp/src/containers/Map/index.jsx
  packages/webapp/src/containers/Map/useMapAssetRenderer.js
  packages/webapp/src/util/google-maps/cleanupListeners.ts
  packages/webapp/src/util/google-maps/debugListeners.ts
Labels: bug

#3743 LF-4172 Create new Time component
  packages/webapp/package.json
  packages/webapp/pnpm-lock.yaml
  packages/webapp/src/assets/images/dateInput/clock.svg
  packages/webapp/src/assets/theme/index.tsx
  packages/webapp/src/components/Inputs/DateTime/index.tsx
  packages/webapp/src/components/Inputs/DateTime/styles.module.scss
  packages/webapp/src/components/Inputs/DateTime/utils.ts
  packages/webapp/src/components/Navigation/styles.module.scss
  packages/webapp/src/main.jsx
  packages/webapp/src/stories/Form/DateTimeInputs/DateInput.stories.tsx
  packages/webapp/src/stories/Form/DateTimeInputs/TimeInput.stories.tsx
  packages/webapp/src/stories/Form/DateTimeInputs/styles.module.scss
Labels: enhancement

#3747 LF-4770 (1): Display flow to approve an IP and create a task from it
  packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
  packages/webapp/src/containers/IrrigationPrescription/useApproveIrrigationPrescription.ts
  packages/webapp/src/containers/irrigationTaskTypesSlice.js
  packages/webapp/src/containers/taskTypeSlice.js
  packages/webapp/src/stories/Form/Unit/SystemUnmatch.stories.jsx
  packages/webapp/src/stories/Pages/Task/TaskDetail/TaskDetail.stories.jsx
  packages/webapp/src/stories/Pages/Tasks/CleaningTaskReadOnly.stories.jsx
  packages/webapp/src/stories/Pages/Tasks/IrrigationTaskReadOnly.stories.jsx
  packages/webapp/src/tests/convertUnits.test.js
  packages/webapp/src/util/convert-units/unit.js
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement

#3751 LF-4764 Add irrigation_prescription_external_id to irrigation_task table
  packages/api/db/migration/20250430202219_add_irrigation_prescription_id_and_permissions.js
  packages/api/src/models/irrigationTaskModel.js
  packages/api/src/routes/irrigationPrescriptionRequestRoute.ts
  packages/api/src/routes/sensorRoute.js
Labels: enhancement

#3746 LF-4768 (3) Display IP Detail - IP Detail Container
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/assets/images/header-chevron-left.svg
  packages/webapp/src/components/Animals/FixedHeaderContainer/styles.module.scss
  packages/webapp/src/components/CropListPage/index.jsx
  packages/webapp/src/components/IrrigationPrescription/index.tsx
  packages/webapp/src/components/IrrigationPrescription/styles.module.scss
  packages/webapp/src/components/IrrigationPrescription/types.ts
  packages/webapp/src/components/Layout/CardLayout.tsx
  packages/webapp/src/components/Layout/layout.module.scss
  packages/webapp/src/components/LocationDetailLayout/PointDetails/Sensor/index.jsx
  packages/webapp/src/components/LocationDetailLayout/PureLocationDetailLayout.jsx
  packages/webapp/src/components/LocationFieldTechnology/index.jsx
  packages/webapp/src/components/LocationTasks/index.jsx
  packages/webapp/src/components/Navigation/styles.module.scss
  packages/webapp/src/components/Navigation/useSectionHeaders.tsx
  packages/webapp/src/components/PageTitle/index.jsx
  packages/webapp/src/components/PageTitle/styles.module.scss
  packages/webapp/src/components/PageTitle/v2/index.jsx
  packages/webapp/src/components/PageTitle/v2/styles.module.scss
  packages/webapp/src/components/Sensor/EditSensor.jsx
  packages/webapp/src/containers/IrrigationPrescription/index.tsx
  packages/webapp/src/containers/IrrigationPrescription/styles.module.scss
  packages/webapp/src/containers/SensorReadings/index.jsx
  packages/webapp/src/containers/SensorReadings/v2/index.tsx
  packages/webapp/src/routes/index.jsx
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement, new translations
