Repository LiteFarmOrg/LiteFarm, pull requests merged in 2025-06, with the labels that each got.

#3793 LF-4835: Soil sampling task read-only view
  packages/webapp/src/components/Task/SoilSampleTask/styles.module.scss
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/containers/slice/taskSlice/soilSampleTaskSlice.js
  packages/webapp/src/containers/taskSlice.js
  packages/webapp/src/store/reducer.js
  packages/webapp/src/util/siteMapConstants.ts
Labels: enhancement

#3778 LF-4802 Finance pages crash when selecting a custom date range and closing the component without clicking away
  packages/webapp/src/components/DateRangeSelector/DateRangeInput.jsx
  packages/webapp/src/components/DateRangeSelector/styles.module.scss
Labels: bug

#3789 LF-4774 Remove mocked sensor data; set up valid defaults; check against real sensor data
  packages/api/src/util/ensemble.js
  packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
  packages/webapp/src/containers/SensorList/useGroupedSensors.ts
  packages/webapp/src/containers/SensorReadings/v2/index.tsx
  packages/webapp/src/containers/SensorReadings/v2/utils.ts
  packages/webapp/src/store/api/types/index.ts
Labels: enhancement

#3798 [Quick Bugfix] Add optional chaining on label localeCompare
  packages/webapp/src/components/Filter/FilterMultiSelectV2/index.tsx
Labels: bug

#3800 Lf 4836 (2) allow associating result document s with task on complete 2
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/ContainerWithIcon/ContainerWithIcon.jsx
  packages/webapp/src/components/Documents/Add/index.jsx
  packages/webapp/src/components/FilePicker/index.tsx
  packages/webapp/src/components/FilePicker/styles.module.scss
  packages/webapp/src/components/FilePicker/useFilePickerUpload.tsx
  packages/webapp/src/components/Loading/Loading.jsx
  packages/webapp/src/components/OrganicCertifierSurvey/CertifierSelection/CertifierSelectionMenu/CertiferSelectionMenuItem/index.jsx
  packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/components/Task/TaskComplete/index.jsx
  packages/webapp/src/components/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Documents/Add/index.jsx
  packages/webapp/src/containers/Documents/DocumentUploader/saga.js
  packages/webapp/src/containers/Documents/Edit/index.jsx
  packages/webapp/src/containers/Task/TaskComplete/StepOne.jsx
  packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
  packages/webapp/src/containers/Task/saga.js
  packages/webapp/src/containers/Task/sagaUtils.js
  packages/webapp/src/containers/taskSlice.js
  packages/webapp/src/stories/Pages/Document/AddDocument.stories.jsx
  packages/webapp/src/stories/Pages/Document/EditDocument.stories.jsx
  packages/webapp/src/stories/Pages/Document/MainDocument.stories.jsx
Labels: new translations

#3808 Fix import of lodash isEqual in documents
  packages/webapp/src/components/Documents/Add/index.jsx
Labels: bug

#3801 LF-4872 Show irrigation system name somewhere on the sensor list
  packages/api/src/util/ensemble.js
  packages/webapp/src/components/LocationFieldTechnology/index.jsx
  packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
  packages/webapp/src/components/Sensor/v2/utils.ts
  packages/webapp/src/containers/SensorList/useGroupedSensors.ts
  packages/webapp/src/containers/SensorReadings/v2/index.tsx
  packages/webapp/src/store/api/types/index.ts
Labels: bug, enhancement

#3804 LF-4873: Issues in custom date range filter for sensor readings
  packages/webapp/src/containers/SensorReadings/v2/Charts/useFormattedSensorReadings.ts
  packages/webapp/src/containers/SensorReadings/v2/utils.ts
  packages/webapp/src/tests/sensorChartUtils.test.js
Labels: bug

#3805 LF-4857 Both selected and de-selected visual map icons overlay for soil samples
  packages/webapp/src/assets/images/map/sensor.svg
  packages/webapp/src/assets/images/map/soil-sample-location-active.svg
  packages/webapp/src/assets/images/map/soil-sample-location-hover.svg
  packages/webapp/src/assets/images/map/soil-sample-location.svg
Labels: bug

#3811 LF-4862 Add back the add task button to location task screen
  packages/webapp/src/components/LocationTasks/index.jsx
  packages/webapp/src/components/LocationTasks/styles.module.scss
  packages/webapp/src/containers/LocationDetails/LocationTasks/index.jsx
Labels: bug

#3812 LF-4871 Sensor KPIs & sensor readings tooltips should be to one decimal place not two
  packages/webapp/src/components/Tile/SensorTile/SensorKPI.tsx
  packages/webapp/src/containers/SensorList/useGroupedSensors.ts
  packages/webapp/src/containers/SensorReadings/v2/utils.ts
  packages/webapp/src/tests/sensorChartUtils.test.js
  packages/webapp/src/util/rounding.js
Labels: bug, enhancement

#3814 LF-4876 The worker is directed to create a location for a soil sample task even though he is not allowed to do this
  packages/webapp/public/locales/en/translation.json
  packages/webapp/src/components/Modals/NoSoilSampleLocationsModal/index.jsx
  packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
Labels: bug, new translations

#3787 LF-4788 (Backend) Create GET endpoint to fetch individual IP from Ensemble
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/controllers/irrigationPrescriptionController.ts
  packages/api/src/middleware/validation/checkIrrigationPrescription.ts
  packages/api/src/models/locationModel.js
  packages/api/src/routes/irrigationPrescriptionRoute.ts
  packages/api/src/types.ts
  packages/api/src/util/ensembleService.ts
  packages/api/src/util/ensembleService.types.ts
  packages/api/src/util/generateMockPrescriptionDetails.ts
  packages/api/src/util/geoUtils.ts
  packages/api/src/util/mockAddonPartner.ts
  packages/api/tests/irrigation_prescription.test.ts
  packages/api/tests/mock.factories.js
Labels: enhancement
